// Hardcoded sample data for the map+date POC.
// Real version would extract this from Wikidata (P585/P580 for date, P625 for coordinates).
export type HistoricalEvent = {
  id: string;
  clue: string;
  name: string;
  explanation: string;
  year: number; // negative = BCE
  lat: number;
  lng: number;
  wikipediaTitle: string;
};

export const POC_EVENTS: HistoricalEvent[] = [
  {
    id: "hastings",
    clue: "A duke sails across the sea from his own duchy, defeats and kills a king in battle, and founds a new ruling dynasty.",
    name: "Battle of Hastings",
    year: 1066,
    lat: 50.91,
    lng: 0.49,
    wikipediaTitle: "Battle_of_Hastings",
    explanation: "William, Duke of Normandy, defeated King Harold II at Hastings, becoming King of England and beginning Norman rule over the country.",
  },
  {
    id: "bastille",
    clue: "Crowds storm a hated fortress-prison, kill its governor, and parade his head on a pike, igniting nationwide upheaval.",
    name: "Storming of the Bastille",
    year: 1789,
    lat: 48.853,
    lng: 2.369,
    wikipediaTitle: "Storming_of_the_Bastille",
    explanation: "Parisians stormed the Bastille fortress-prison, a symbol of royal tyranny, marking the start of the French Revolution.",
  },
  {
    id: "constantinople",
    clue: "After a 53-day siege, an ancient capital falls, ending an empire that had lasted more than a thousand years.",
    name: "Fall of Constantinople",
    year: 1453,
    lat: 41.008,
    lng: 28.978,
    wikipediaTitle: "Fall_of_Constantinople",
    explanation: "Ottoman forces under Sultan Mehmed II captured Constantinople after a 53-day siege, ending the Byzantine Empire after over 1,000 years.",
  },
  {
    id: "trafalgar",
    clue: "A mortally wounded admiral's fleet destroys two combined enemy fleets off a rocky cape, securing naval dominance for a century.",
    name: "Battle of Trafalgar",
    year: 1805,
    lat: 36.18,
    lng: -6.03,
    wikipediaTitle: "Battle_of_Trafalgar",
    explanation: "The British fleet under Admiral Nelson destroyed the combined French and Spanish fleets off Cape Trafalgar, securing British naval supremacy for a century.",
  },
  {
    id: "wright",
    clue: "On windswept coastal dunes, two brothers achieve the first sustained, controlled flight of a powered aircraft.",
    name: "Wright Brothers' First Flight",
    year: 1903,
    lat: 36.0128,
    lng: -75.6699,
    wikipediaTitle: "Wright_Flyer",
    explanation: "Orville and Wilbur Wright achieved the first sustained, controlled flight of a powered aircraft at Kitty Hawk, North Carolina.",
  },
  {
    id: "chernobyl",
    clue: "A reactor at a power plant explodes and burns for over a week, causing the worst nuclear accident in history.",
    name: "Chernobyl Disaster",
    year: 1986,
    lat: 51.389,
    lng: 30.099,
    wikipediaTitle: "Chernobyl_disaster",
    explanation: "A reactor at the Chernobyl Nuclear Power Plant exploded, releasing massive radioactive contamination across Europe in the worst nuclear disaster in history.",
  },
  {
    id: "machupicchu",
    clue: "Local farmers guide a foreign historian to a citadel abandoned centuries earlier, hidden high in the mountains.",
    name: "Machu Picchu brought to world attention",
    year: 1911,
    lat: -13.1631,
    lng: -72.545,
    wikipediaTitle: "Machu_Picchu",
    explanation: "American historian Hiram Bingham was guided to the ruins of Machu Picchu by local farmers, bringing the Incan citadel to international attention.",
  },
  {
    id: "romefire",
    clue: "A fire burns an ancient capital's wooden districts for six days, and its ruler is later blamed for scapegoating a religious minority.",
    name: "Great Fire of Rome",
    year: 64,
    lat: 41.9028,
    lng: 12.4964,
    wikipediaTitle: "Great_Fire_of_Rome",
    explanation: "A massive fire burned through Rome for six days, destroying much of the city; Emperor Nero was later blamed for using it as a pretext to persecute Christians.",
  },
  {
    id: "waterloo",
    clue: "A former emperor makes his last stand against a coalition of three armies, on a muddy field near a capital, ending his rule for good.",
    name: "Battle of Waterloo",
    year: 1815,
    lat: 50.68,
    lng: 4.411,
    wikipediaTitle: "Battle_of_Waterloo",
    explanation: "A coalition of British, Dutch, and Prussian forces defeated Napoleon Bonaparte near Waterloo, ending his rule and the Napoleonic Wars for good.",
  },
  {
    id: "titanic",
    clue: "A liner touted as 'unsinkable' strikes an iceberg on its maiden voyage and sinks overnight, killing over 1,500 aboard.",
    name: "Sinking of the Titanic",
    year: 1912,
    lat: 41.7325,
    lng: -49.9469,
    wikipediaTitle: "Sinking_of_the_Titanic",
    explanation: "The RMS Titanic struck an iceberg in the North Atlantic and sank overnight, killing over 1,500 people on its maiden voyage.",
  },
  {
    id: "pearlharbor",
    clue: "A surprise air raid by carrier-launched planes cripples an island naval base, drawing a reluctant nation into a world war.",
    name: "Attack on Pearl Harbor",
    year: 1941,
    lat: 21.3645,
    lng: -157.9498,
    wikipediaTitle: "Attack_on_Pearl_Harbor",
    explanation: "Japan launched a surprise attack on the US naval base at Pearl Harbor, Hawaii, bringing the United States into World War II.",
  },
  {
    id: "tutankhamun",
    clue: "An archaeologist finds a young ruler's tomb almost untouched after more than 3,000 years.",
    name: "Discovery of Tutankhamun's Tomb",
    year: 1922,
    lat: 25.7402,
    lng: 32.6014,
    wikipediaTitle: "Tutankhamun",
    explanation: "Archaeologist Howard Carter discovered the largely intact tomb of the young pharaoh Tutankhamun in the Valley of the Kings, Egypt.",
  },
  {
    id: "berlinwall",
    clue: "Crowds tear down a concrete barrier that had divided a city in two for 28 years.",
    name: "Fall of the Berlin Wall",
    year: 1989,
    lat: 52.5163,
    lng: 13.3777,
    wikipediaTitle: "Fall_of_the_Berlin_Wall",
    explanation: "East German authorities opened the Berlin Wall after mass protests, and jubilant crowds began tearing it down, symbolizing the end of the Cold War divide.",
  },
  {
    id: "krakatoa",
    clue: "A volcanic island in a narrow strait erupts in what's still the loudest sound ever recorded, then drowns nearby coasts in tsunamis.",
    name: "Eruption of Krakatoa",
    year: 1883,
    lat: -6.1022,
    lng: 105.423,
    wikipediaTitle: "Krakatoa",
    explanation: "The volcanic island of Krakatoa erupted catastrophically, producing a sound heard thousands of kilometres away and triggering tsunamis that killed tens of thousands.",
  },
  {
    id: "columbus",
    clue: "A navigator sailing under a foreign flag lands on a small island, insisting until his death that he had reached the Indies.",
    name: "Columbus Reaches the Americas",
    year: 1492,
    lat: 24.0567,
    lng: -74.4959,
    wikipediaTitle: "Christopher_Columbus",
    explanation: "Christopher Columbus's expedition, sailing for Spain, landed on an island in the Bahamas, beginning sustained European contact with the Americas.",
  },
  {
    id: "stalingrad",
    clue: "A brutal months-long siege ends with an entire encircled army forced to surrender, a turning point of a world war.",
    name: "Battle of Stalingrad",
    year: 1943,
    lat: 48.708,
    lng: 44.5133,
    wikipediaTitle: "Battle_of_Stalingrad",
    explanation: "The Battle of Stalingrad was one of the bloodiest battles in history; the Soviet victory marked a major turning point against Nazi Germany.",
  },
  {
    id: "indianindependence",
    clue: "At the stroke of midnight, a newly freed nation's first leader gives his 'tryst with destiny' speech to a crowd in its capital.",
    name: "Indian Independence",
    year: 1947,
    lat: 28.6139,
    lng: 77.209,
    wikipediaTitle: "Indian_independence_movement",
    explanation: "India became independent from British colonial rule, with Prime Minister Jawaharlal Nehru delivering his famous 'Tryst with Destiny' speech at midnight.",
  },
  {
    id: "hearttransplant",
    clue: "A surgeon performs the first human heart transplant in a coastal city below a flat-topped mountain.",
    name: "First Heart Transplant",
    year: 1967,
    lat: -33.9249,
    lng: 18.4241,
    wikipediaTitle: "Christiaan_Barnard",
    explanation: "South African surgeon Christiaan Barnard performed the world's first human-to-human heart transplant at Groote Schuur Hospital in Cape Town.",
  },
  {
    id: "gettysburg",
    clue: "A three-day clash in a small town leaves roughly 50,000 casualties, the bloodiest battle of a civil war.",
    name: "Battle of Gettysburg",
    year: 1863,
    lat: 39.8309,
    lng: -77.2311,
    wikipediaTitle: "Battle_of_Gettysburg",
    explanation: "The Battle of Gettysburg was the bloodiest battle of the American Civil War and a turning point in the Union's favor.",
  },
  {
    id: "franzferdinand",
    clue: "The assassination of an archduke and his wife during a state visit sets off a chain reaction toward world war.",
    name: "Assassination of Archduke Franz Ferdinand",
    year: 1914,
    lat: 43.8563,
    lng: 18.4131,
    wikipediaTitle: "Assassination_of_Archduke_Franz_Ferdinand",
    explanation: "The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo triggered a chain of alliances that led to World War I.",
  },
  {
    id: "marathon",
    clue: "A heavily outnumbered army halts an invasion on a coastal plain; a runner's dash to the capital afterward later gives its name to a foot race.",
    name: "Battle of Marathon",
    year: -490,
    lat: 38.15,
    lng: 23.98,
    wikipediaTitle: "Battle_of_Marathon",
    explanation: "Athenian forces defeated a much larger Persian invasion force at Marathon; legend holds a messenger then ran to Athens to announce victory.",
  },
  {
    id: "thermopylae",
    clue: "A small force holds a narrow mountain pass for three days until a local betrays a hidden path, letting the invading army surround them.",
    name: "Battle of Thermopylae",
    year: -480,
    lat: 38.798,
    lng: 22.537,
    wikipediaTitle: "Battle_of_Thermopylae",
    explanation: "A small Greek force led by King Leonidas of Sparta held off a massive Persian army at the narrow pass of Thermopylae for three days.",
  },
  {
    id: "caesarassassination",
    clue: "A dictator is stabbed some twenty-three times by senators inside a theatre complex, on the day of a fateful assembly.",
    name: "Assassination of Julius Caesar",
    year: -44,
    lat: 41.8963,
    lng: 12.4778,
    wikipediaTitle: "Assassination_of_Julius_Caesar",
    explanation: "Roman senators assassinated Julius Caesar in the Theatre of Pompey, fearing his growing power.",
  },
  {
    id: "pompeii",
    clue: "A volcanic eruption buries a town under ash in hours, preserving it so well that plaster poured into the ash later recreates victims' exact poses.",
    name: "Destruction of Pompeii",
    year: 79,
    lat: 40.7461,
    lng: 14.4989,
    wikipediaTitle: "Pompeii",
    explanation: "The eruption of Mount Vesuvius buried the Roman towns of Pompeii and Herculaneum under ash and pumice, preserving them remarkably intact.",
  },
  {
    id: "actium",
    clue: "A naval battle pits a queen and her lover, a general, against his former ally, deciding who will rule an empire.",
    name: "Battle of Actium",
    year: -31,
    lat: 38.9432,
    lng: 20.7376,
    wikipediaTitle: "Battle_of_Actium",
    explanation: "Octavian's fleet defeated the combined forces of Mark Antony and Cleopatra at Actium, paving the way for the Roman Empire.",
  },
  {
    id: "greatpyramid",
    clue: "Workers complete the tallest structure on Earth, a record the monument will hold for almost 4,000 years.",
    name: "Great Pyramid of Giza completed",
    year: -2560,
    lat: 29.9792,
    lng: 31.1342,
    wikipediaTitle: "Great_Pyramid_of_Giza",
    explanation: "The Great Pyramid of Giza, built as a tomb for Pharaoh Khufu, was the tallest man-made structure in the world for nearly 4,000 years.",
  },
  {
    id: "firstolympics",
    clue: "Athletes gather at a sacred sanctuary for the first recorded games honoring the king of the gods.",
    name: "First Olympic Games",
    year: -776,
    lat: 37.6383,
    lng: 21.63,
    wikipediaTitle: "Ancient_Olympic_Games",
    explanation: "The first recorded Olympic Games were held at Olympia, Greece, as a religious festival honoring Zeus.",
  },
  {
    id: "cannae",
    clue: "A pincer maneuver lets a smaller army encircle and destroy a much larger one in a single day, among the deadliest in ancient warfare.",
    name: "Battle of Cannae",
    year: -216,
    lat: 41.3021,
    lng: 16.1447,
    wikipediaTitle: "Battle_of_Cannae",
    explanation: "Hannibal's Carthaginian army encircled and destroyed a much larger Roman army at Cannae, one of history's greatest tactical victories.",
  },
  {
    id: "rubicon",
    clue: "A general marches his legion across a small river, defying the law and igniting a civil war.",
    name: "Crossing of the Rubicon",
    year: -49,
    lat: 44.13,
    lng: 12.36,
    wikipediaTitle: "Crossing_the_Rubicon",
    explanation: "Julius Caesar led his army across the Rubicon River into Italy, defying Roman law and starting a civil war, giving rise to the phrase 'crossing the Rubicon.'",
  },
  {
    id: "gaugamela",
    clue: "A young conqueror's smaller army routs a much larger imperial force on an open plain, effectively ending a centuries-old empire.",
    name: "Battle of Gaugamela",
    year: -331,
    lat: 36.3639,
    lng: 43.4331,
    wikipediaTitle: "Battle_of_Gaugamela",
    explanation: "Alexander the Great's outnumbered army decisively defeated Darius III of Persia at Gaugamela, effectively ending the Achaemenid Empire.",
  },
  {
    id: "magnacarta",
    clue: "Rebellious barons force a king to seal a charter limiting his own power, in a riverside meadow.",
    name: "Signing of the Magna Carta",
    year: 1215,
    lat: 51.4432,
    lng: -0.5697,
    wikipediaTitle: "Magna_Carta",
    explanation: "English barons forced King John to seal the Magna Carta at Runnymede, establishing the principle that the king was subject to the law.",
  },
  {
    id: "sackofrome410",
    clue: "An invading king's army breaches the walls of an ancient capital for the first time in nearly 800 years.",
    name: "Sack of Rome",
    year: 410,
    lat: 41.9028,
    lng: 12.4964,
    wikipediaTitle: "Sack_of_Rome_(410)",
    explanation: "The Visigoths under King Alaric sacked Rome, the first time the city had fallen to a foreign enemy in nearly 800 years.",
  },
  {
    id: "baghdadfounding",
    clue: "A religious and political leader founds a new round city destined to become a center of learning and trade.",
    name: "Founding of Baghdad",
    year: 762,
    lat: 33.3152,
    lng: 44.3661,
    wikipediaTitle: "Baghdad",
    explanation: "The Abbasid Caliph al-Mansur founded Baghdad as his new capital, which grew into a major center of trade, science, and culture.",
  },
  {
    id: "genghiskhan",
    clue: "A tribal leader takes a new title as he's proclaimed ruler of all the steppe peoples at a great assembly.",
    name: "Genghis Khan proclaimed ruler",
    year: 1206,
    lat: 47.5,
    lng: 110.9,
    wikipediaTitle: "Genghis_Khan",
    explanation: "At a great assembly (kurultai), Temüjin was proclaimed Genghis Khan, ruler of all the Mongol and Turkic tribes, founding the Mongol Empire.",
  },
  {
    id: "blackdeath",
    clue: "Rats infested with plague slip ashore from trading ships at a port, unleashing a pandemic that will kill roughly a third of the population.",
    name: "Black Death reaches Europe",
    year: 1347,
    lat: 38.1938,
    lng: 15.554,
    wikipediaTitle: "Black_Death",
    explanation: "Ships carrying plague-infected rats docked in Messina, Sicily, introducing the Black Death to Europe, which killed roughly a third of the population.",
  },
  {
    id: "fallofgranada",
    clue: "The last stronghold of a centuries-old kingdom surrenders to a royal army, completing a reconquest that had lasted centuries.",
    name: "Fall of Granada",
    year: 1492,
    lat: 37.1773,
    lng: -3.5986,
    wikipediaTitle: "Granada_War",
    explanation: "The Emirate of Granada, the last Muslim stronghold in Spain, surrendered to the Catholic Monarchs, completing the centuries-long Reconquista.",
  },
  {
    id: "agincourt",
    clue: "A heavily outnumbered army of longbowmen devastates a mounted force in the mud.",
    name: "Battle of Agincourt",
    year: 1415,
    lat: 50.466,
    lng: 2.143,
    wikipediaTitle: "Battle_of_Agincourt",
    explanation: "King Henry V's outnumbered English army, largely archers, decisively defeated the French at Agincourt during the Hundred Years' War.",
  },
  {
    id: "siegeoforleans",
    clue: "A 17-year-old peasant girl leads an army to lift a months-long siege on a besieged city.",
    name: "Siege of Orléans lifted",
    year: 1429,
    lat: 47.9029,
    lng: 1.9093,
    wikipediaTitle: "Siege_of_Orléans",
    explanation: "A 17-year-old Joan of Arc inspired French forces to lift the English siege of Orléans, a turning point in the Hundred Years' War.",
  },
  {
    id: "vascodagama",
    clue: "An explorer's fleet rounds a great southern cape, completing the first direct sea route to a distant spice-trading port.",
    name: "Vasco da Gama reaches Calicut",
    year: 1498,
    lat: 11.2588,
    lng: 75.7804,
    wikipediaTitle: "Vasco_da_Gama",
    explanation: "Portuguese explorer Vasco da Gama arrived at Calicut, India, having found the first direct sea route from Europe to Asia.",
  },
  {
    id: "magellancircumnavigation",
    clue: "Only one ship and a handful of sailors return from an expedition, having completed the first sail all the way around the globe.",
    name: "Magellan expedition completes circumnavigation",
    year: 1522,
    lat: 36.7783,
    lng: -6.3531,
    wikipediaTitle: "Ferdinand_Magellan",
    explanation: "The Victoria, the last surviving ship of Ferdinand Magellan's expedition, returned to Spain, completing the first circumnavigation of the globe.",
  },
  {
    id: "mayflower",
    clue: "Passengers sign a compact to govern themselves while still aboard ship, before anyone sets foot on land.",
    name: "Mayflower lands at Plymouth",
    year: 1620,
    lat: 41.9584,
    lng: -70.6673,
    wikipediaTitle: "Mayflower",
    explanation: "Pilgrim settlers aboard the Mayflower landed at Plymouth, founding one of the first permanent English colonies in North America.",
  },
  {
    id: "greatfireoflondon",
    clue: "A bakery fire spreads through a densely packed wooden city, burning for four days.",
    name: "Great Fire of London",
    year: 1666,
    lat: 51.5099,
    lng: -0.0899,
    wikipediaTitle: "Great_Fire_of_London",
    explanation: "A fire that started in a bakery on Pudding Lane spread through London, destroying most of the medieval city over four days.",
  },
  {
    id: "newtonprincipia",
    clue: "A reclusive scholar publishes a work laying out the laws that govern motion and gravity.",
    name: "Newton publishes the Principia",
    year: 1687,
    lat: 52.2043,
    lng: 0.1218,
    wikipediaTitle: "Philosophiæ_Naturalis_Principia_Mathematica",
    explanation: "Isaac Newton published the Principia Mathematica, laying out his laws of motion and universal gravitation.",
  },
  {
    id: "stpetersburgfounding",
    clue: "A ruler founds a new capital on marshland, intended as a window to the West.",
    name: "Founding of St. Petersburg",
    year: 1703,
    lat: 59.9311,
    lng: 30.3609,
    wikipediaTitle: "Saint_Petersburg",
    explanation: "Tsar Peter the Great founded St. Petersburg on the Baltic coast as Russia's 'window to the West,' later making it the imperial capital.",
  },
  {
    id: "usdeclaration",
    clue: "Delegates sign a document formally breaking away from a distant king's rule, in a red-brick hall.",
    name: "US Declaration of Independence signed",
    year: 1776,
    lat: 39.9483,
    lng: -75.15,
    wikipediaTitle: "United_States_Declaration_of_Independence",
    explanation: "Delegates in Philadelphia adopted the Declaration of Independence, formally announcing the American colonies' break from British rule.",
  },
  {
    id: "winterpalace",
    clue: "Revolutionary forces storm an ornate palace almost unopposed, toppling a provisional government overnight.",
    name: "Storming of the Winter Palace",
    year: 1917,
    lat: 59.9398,
    lng: 30.3146,
    wikipediaTitle: "October_Revolution",
    explanation: "Bolshevik revolutionaries stormed the Winter Palace in Petrograd, overthrowing Russia's Provisional Government.",
  },
  {
    id: "louisxviexecution",
    clue: "A deposed king is executed by guillotine before a large crowd in a grand public square.",
    name: "Execution of Louis XVI",
    year: 1793,
    lat: 48.8656,
    lng: 2.3212,
    wikipediaTitle: "Louis_XVI",
    explanation: "King Louis XVI of France was executed by guillotine in Paris during the French Revolution.",
  },
  {
    id: "congressofvienna",
    clue: "Great powers meet in a grand city to redraw the map after years of war, so busy with balls that a wit of the time quips it dances but never advances.",
    name: "Congress of Vienna opens",
    year: 1814,
    lat: 48.2082,
    lng: 16.3738,
    wikipediaTitle: "Congress_of_Vienna",
    explanation: "The Congress of Vienna brought European powers together to redraw the continent's borders after the Napoleonic Wars, and its endless balls were so notorious that a diplomat quipped, 'The congress dances, but it does not walk.'",
  },
  {
    id: "ayacucho",
    clue: "A decisive battle high in the mountains all but ends colonial rule across a continent.",
    name: "Battle of Ayacucho",
    year: 1824,
    lat: -13.16,
    lng: -74.22,
    wikipediaTitle: "Battle_of_Ayacucho",
    explanation: "The decisive Battle of Ayacucho in the Peruvian Andes effectively ended Spanish colonial rule in South America.",
  },
  {
    id: "greekindependence",
    clue: "Clergy and rebels raise a flag at a mountain monastery, declaring revolt against an empire.",
    name: "Greek War of Independence declared",
    year: 1821,
    lat: 37.98,
    lng: 22.11,
    wikipediaTitle: "Greek_War_of_Independence",
    explanation: "Greek rebels declared independence from the Ottoman Empire, sparking the Greek War of Independence.",
  },
  {
    id: "suezcanal",
    clue: "A canal is dug through flat desert with no locks, linking two seas and shortening travel between continents.",
    name: "Opening of the Suez Canal",
    year: 1869,
    lat: 31.2653,
    lng: 32.3019,
    wikipediaTitle: "Suez_Canal",
    explanation: "The Suez Canal opened after a decade of construction led by French diplomat Ferdinand de Lesseps. Dug at sea level with no locks, it let ships sail directly between the Mediterranean and Red Sea instead of circling all the way around Africa, transforming global trade overnight.",
  },
  {
    id: "transatlanticcable",
    clue: "Engineers complete a cable strung across the ocean floor, connecting two continents by wire.",
    name: "First transatlantic telegraph cable completed",
    year: 1858,
    lat: 51.9333,
    lng: -10.3333,
    wikipediaTitle: "Transatlantic_telegraph_cable",
    explanation: "The first transatlantic telegraph cable was completed, allowing near-instant communication between Europe and North America for the first time.",
  },
  {
    id: "darwinorigin",
    clue: "A naturalist publishes a controversial book proposing that species evolve through natural selection.",
    name: "Darwin publishes On the Origin of Species",
    year: 1859,
    lat: 51.5074,
    lng: -0.1278,
    wikipediaTitle: "On_the_Origin_of_Species",
    explanation: "Charles Darwin published 'On the Origin of Species,' introducing his theory of evolution by natural selection.",
  },
  {
    id: "meijirestoration",
    clue: "Imperial rule is restored in an ancient capital, ending centuries of rule by hereditary military governors.",
    name: "Meiji Restoration proclaimed",
    year: 1868,
    lat: 35.0116,
    lng: 135.7681,
    wikipediaTitle: "Meiji_Restoration",
    explanation: "The Meiji Restoration restored imperial rule in Japan, ending centuries of shogunate government and beginning rapid modernization.",
  },
  {
    id: "siegeofparis1871",
    clue: "A four-month siege forces a capital to surrender, hastening the unification of a new great power.",
    name: "Siege of Paris ends",
    year: 1871,
    lat: 48.8566,
    lng: 2.3522,
    wikipediaTitle: "Siege_of_Paris_(1870–1871)",
    explanation: "The Prussian siege of Paris ended with the city's surrender, a decisive moment in the Franco-Prussian War.",
  },
  {
    id: "bellfirstcall",
    clue: "An inventor makes the first successful call on a voice-transmitting device, telling his assistant in the next room to come see him.",
    name: "Bell's first telephone call",
    year: 1876,
    lat: 42.3601,
    lng: -71.0589,
    wikipediaTitle: "Alexander_Graham_Bell",
    explanation: "Alexander Graham Bell made the first successful telephone call, famously saying 'Mr. Watson, come here, I want to see you.'",
  },
  {
    id: "eiffeltower",
    clue: "A controversial iron tower is completed for a world's fair, meant to stand for only twenty years.",
    name: "Eiffel Tower completed",
    year: 1889,
    lat: 48.8584,
    lng: 2.2945,
    wikipediaTitle: "Eiffel_Tower",
    explanation: "The Eiffel Tower was completed as the entrance arch for the World's Fair in Paris, and was meant to be dismantled after 20 years.",
  },
  {
    id: "battleofsomme",
    clue: "One of history's bloodiest battles begins along a quiet river valley, inflicting over a million casualties on both sides.",
    name: "Battle of the Somme begins",
    year: 1916,
    lat: 50.0,
    lng: 2.75,
    wikipediaTitle: "Battle_of_the_Somme",
    explanation: "The Battle of the Somme was one of the bloodiest battles of World War I, with over a million casualties on both sides.",
  },
  {
    id: "armistice1918",
    clue: "Delegates sign an armistice inside a railway carriage in a forest, ending four years of war.",
    name: "Armistice signed ending WWI",
    year: 1918,
    lat: 49.4167,
    lng: 2.9,
    wikipediaTitle: "Armistice_of_11_November_1918",
    explanation: "An armistice signed in a railway carriage near Compiègne, France, ended fighting on the Western Front of World War I.",
  },
  {
    id: "treatyofversailles",
    clue: "Diplomats sign a peace treaty inside a lavish palace, formally ending a world war and imposing harsh terms on the defeated power.",
    name: "Treaty of Versailles signed",
    year: 1919,
    lat: 48.8049,
    lng: 2.1204,
    wikipediaTitle: "Treaty_of_Versailles",
    explanation: "The Treaty of Versailles, signed in the Hall of Mirrors, formally ended World War I and imposed harsh terms on Germany.",
  },
  {
    id: "gallipoli",
    clue: "Allied troops land on a rugged peninsula, beginning an eight-month campaign that ends in a full withdrawal.",
    name: "Gallipoli landing",
    year: 1915,
    lat: 40.15,
    lng: 26.35,
    wikipediaTitle: "Gallipoli_campaign",
    explanation: "Allied troops landed on the Gallipoli peninsula in an attempt to knock the Ottoman Empire out of World War I; the campaign ended in failure.",
  },
  {
    id: "wallstreetcrash",
    clue: "Panicked investors trigger a stock market collapse on a narrow financial street, ushering in a decade-long economic depression.",
    name: "Wall Street Crash",
    year: 1929,
    lat: 40.7075,
    lng: -74.0113,
    wikipediaTitle: "Wall_Street_Crash_of_1929",
    explanation: "The Wall Street Crash wiped out billions in value and triggered the Great Depression.",
  },
  {
    id: "hitlerchancellor",
    clue: "An aging president reluctantly appoints an extremist party leader as head of government.",
    name: "Hitler becomes Chancellor",
    year: 1933,
    lat: 52.52,
    lng: 13.405,
    wikipediaTitle: "Adolf_Hitler",
    explanation: "German President Paul von Hindenburg appointed Adolf Hitler as Chancellor, a key step in the Nazi rise to power.",
  },
  {
    id: "dday",
    clue: "Allied forces launch the largest seaborne invasion in history, storming a stretch of beaches at dawn.",
    name: "D-Day landings",
    year: 1944,
    lat: 49.35,
    lng: -0.8,
    wikipediaTitle: "Normandy_landings",
    explanation: "Allied forces landed on the beaches of Normandy in the largest seaborne invasion in history, opening a decisive front in World War II.",
  },
  {
    id: "hiroshima",
    clue: "A single bomb devastates a city in an instant, killing tens of thousands immediately and ushering in the nuclear age.",
    name: "Atomic bombing of Hiroshima",
    year: 1945,
    lat: 34.3955,
    lng: 132.4536,
    wikipediaTitle: "Atomic_bombings_of_Hiroshima_and_Nagasaki",
    explanation: "The United States dropped an atomic bomb on Hiroshima, Japan, killing tens of thousands instantly and leading to Japan's surrender.",
  },
  {
    id: "germansurrender",
    clue: "Military leaders sign an unconditional surrender inside a schoolhouse, ending years of war.",
    name: "Surrender of Nazi Germany",
    year: 1945,
    lat: 49.2583,
    lng: 4.0317,
    wikipediaTitle: "German_Instrument_of_Surrender",
    explanation: "German military leaders signed an unconditional surrender in Reims, France, ending World War II in Europe.",
  },
  {
    id: "munichagreement",
    clue: "Leaders sign an agreement ceding a border region to avoid another war, a deal broken within the year.",
    name: "Munich Agreement signed",
    year: 1938,
    lat: 48.1351,
    lng: 11.582,
    wikipediaTitle: "Munich_Agreement",
    explanation: "The Munich Agreement allowed Nazi Germany to annex the Sudetenland from Czechoslovakia, in a failed attempt at appeasement.",
  },
  {
    id: "kristallnacht",
    clue: "Mobs smash the windows of Jewish-owned shops and synagogues in a coordinated night of violence.",
    name: "Kristallnacht",
    year: 1938,
    lat: 52.52,
    lng: 13.405,
    wikipediaTitle: "Kristallnacht",
    explanation: "Nazi paramilitaries and civilians attacked Jewish homes, businesses, and synagogues across Germany overnight in a pogrom known as Kristallnacht.",
  },
  {
    id: "warsawghetto",
    clue: "Poorly armed residents of a sealed-off district rise up against occupying forces, in the largest armed revolt of the Holocaust.",
    name: "Warsaw Ghetto Uprising begins",
    year: 1943,
    lat: 52.2297,
    lng: 21.0122,
    wikipediaTitle: "Warsaw_Ghetto_Uprising",
    explanation: "Jewish residents of the Warsaw Ghetto launched an armed uprising against Nazi forces, the largest single act of Jewish resistance during the Holocaust.",
  },
  {
    id: "auschwitzliberation",
    clue: "Soldiers advancing from the east liberate the largest Nazi camp, where over a million were killed, revealing the scale of the horror to the world.",
    name: "Liberation of Auschwitz",
    year: 1945,
    lat: 50.0359,
    lng: 19.1782,
    wikipediaTitle: "Auschwitz_concentration_camp",
    explanation: "Soviet troops liberated the Auschwitz concentration camp, revealing the full horror of the Nazi Holocaust to the world.",
  },
  {
    id: "cubanmissilecrisis",
    clue: "Spy planes photograph secret missile sites on a small island, triggering a tense 13-day naval blockade.",
    name: "Cuban Missile Crisis",
    year: 1962,
    lat: 23.1136,
    lng: -82.3666,
    wikipediaTitle: "Cuban_Missile_Crisis",
    explanation: "The discovery of Soviet nuclear missiles in Cuba triggered a tense 13-day standoff between the US and USSR, among the closest the world came to nuclear war.",
  },
  {
    id: "jfkassassination",
    clue: "A president is shot while riding in an open car through a downtown plaza.",
    name: "Assassination of JFK",
    year: 1963,
    lat: 32.7799,
    lng: -96.8083,
    wikipediaTitle: "Assassination_of_John_F._Kennedy",
    explanation: "US President John F. Kennedy was assassinated while riding in a motorcade through Dealey Plaza in Dallas, Texas.",
  },
  {
    id: "apollo11launch",
    clue: "A towering rocket lifts off from a coastal launch pad, carrying the crew who will become the first humans ever to set foot on another world.",
    name: "Apollo 11 launches for the Moon",
    year: 1969,
    lat: 28.5721,
    lng: -80.648,
    wikipediaTitle: "Apollo_11",
    explanation: "Apollo 11 launched from Cape Canaveral, Florida, carrying the astronauts who would become the first humans to land on the Moon.",
  },
  {
    id: "fallofsaigon",
    clue: "The last helicopters evacuate staff from an embassy roof as the capital falls.",
    name: "Fall of Saigon",
    year: 1975,
    lat: 10.7769,
    lng: 106.7009,
    wikipediaTitle: "Fall_of_Saigon",
    explanation: "North Vietnamese forces captured Saigon, ending the Vietnam War and prompting a chaotic evacuation of the US embassy.",
  },
  {
    id: "mlkassassination",
    clue: "A civil rights leader is shot while standing on a motel balcony.",
    name: "Assassination of Martin Luther King Jr.",
    year: 1968,
    lat: 35.133,
    lng: -90.0568,
    wikipediaTitle: "Assassination_of_Martin_Luther_King_Jr.",
    explanation: "Civil rights leader Martin Luther King Jr. was assassinated on the balcony of the Lorraine Motel in Memphis, Tennessee.",
  },
  {
    id: "mandelareleased",
    clue: "After 27 years, a political prisoner walks free from a prison farm, raising his fist to a waiting crowd.",
    name: "Nelson Mandela released from prison",
    year: 1990,
    lat: -33.7326,
    lng: 18.9612,
    wikipediaTitle: "Nelson_Mandela",
    explanation: "Nelson Mandela was released after 27 years in prison, becoming a global symbol of the fight against apartheid in South Africa.",
  },
  {
    id: "tiananmen",
    clue: "A lone protester stands before a column of tanks near a vast public square.",
    name: "Tiananmen Square protests",
    year: 1989,
    lat: 39.9054,
    lng: 116.3976,
    wikipediaTitle: "Tiananmen_Square_protests_of_1989",
    explanation: "During the Tiananmen Square protests, an unidentified man famously stood in front of a column of tanks, becoming an enduring image of resistance.",
  },
  {
    id: "prcfounding",
    clue: "A revolutionary leader proclaims a new republic from a gate over one of the world's largest public squares, raising a new flag for the first time.",
    name: "Founding of the People's Republic of China",
    year: 1949,
    lat: 39.9054,
    lng: 116.3976,
    wikipediaTitle: "Proclamation_of_the_People's_Republic_of_China",
    explanation: "Mao Zedong proclaimed the founding of the People's Republic of China from the Tiananmen gate in Beijing, as the newly designed five-star flag was raised over the square for the first time.",
  },
  {
    id: "rosettastone",
    clue: "Soldiers rebuilding a fort unearth a slab inscribed in three different scripts that will one day unlock an ancient language.",
    name: "Rosetta Stone discovered",
    year: 1799,
    lat: 31.4044,
    lng: 30.4164,
    wikipediaTitle: "Rosetta_Stone",
    explanation: "French soldiers rebuilding a fort near Rosetta, Egypt, discovered a stone inscribed in three scripts, which later allowed scholars to decipher Egyptian hieroglyphs.",
  },
  {
    id: "penicillin",
    clue: "A scientist notices mold has killed bacteria in a forgotten petri dish, and medicine changes forever.",
    name: "Fleming discovers penicillin",
    year: 1928,
    lat: 51.5177,
    lng: -0.1741,
    wikipediaTitle: "Alexander_Fleming",
    explanation: "Alexander Fleming noticed that mold contaminating a petri dish had killed surrounding bacteria, leading to the discovery of penicillin, the first antibiotic.",
  },
  {
    id: "poliovaccine",
    clue: "Researchers announce that a new polio vaccine, tested in the largest medical field trial in history on over a million children, has proven safe and effective.",
    name: "Polio vaccine trial success announced",
    year: 1955,
    lat: 42.2808,
    lng: -83.743,
    wikipediaTitle: "Polio_vaccine",
    explanation: "Researchers announced that Jonas Salk's polio vaccine had proven safe and effective, a breakthrough against a disease that paralyzed millions of children each year, and it triggered an immediate nationwide rush to manufacture and distribute doses.",
  },
  {
    id: "dnadiscovery",
    clue: "Two young researchers announce they've worked out the twisted-ladder structure of heredity's molecule.",
    name: "DNA double helix discovery announced",
    year: 1953,
    lat: 52.2043,
    lng: 0.1218,
    wikipediaTitle: "DNA",
    explanation: "James Watson and Francis Crick announced they had determined the double helix structure of DNA, a landmark discovery in biology.",
  },
  {
    id: "sputnik",
    clue: "A beeping metal sphere launches into orbit from a remote desert steppe, kicking off a space race.",
    name: "Sputnik 1 launched",
    year: 1957,
    lat: 45.9646,
    lng: 63.3052,
    wikipediaTitle: "Sputnik_1",
    explanation: "The Soviet Union launched Sputnik 1, the first artificial satellite, from Baikonur Cosmodrome, starting the Space Race.",
  },
  {
    id: "plainsofabraham",
    clue: "Two young generals both fall in a short, decisive battle fought on a plateau above a river.",
    name: "Battle of the Plains of Abraham",
    year: 1759,
    lat: 46.8123,
    lng: -71.2145,
    wikipediaTitle: "Battle_of_the_Plains_of_Abraham",
    explanation: "British forces defeated the French on the Plains of Abraham near Quebec City, a decisive battle in the fight for control of Canada.",
  },
  {
    id: "louisianapurchase",
    clue: "Diplomats sign a treaty in a grand foreign capital, buying a vast territory for $15 million and doubling a young nation's size overnight.",
    name: "Louisiana Purchase treaty signed",
    year: 1803,
    lat: 48.8566,
    lng: 2.3522,
    wikipediaTitle: "Louisiana_Purchase",
    explanation: "The United States purchased the vast Louisiana Territory from France for $15 million, roughly doubling the country's size.",
  },
  {
    id: "panamacanal",
    clue: "Massive locks lift ships across a disease-plagued jungle isthmus, linking two oceans after decades of work.",
    name: "Panama Canal opens",
    year: 1914,
    lat: 9.08,
    lng: -79.68,
    wikipediaTitle: "Panama_Canal",
    explanation: "The Panama Canal opened after decades of construction, creating a shortcut between the Atlantic and Pacific Oceans.",
  },
  {
    id: "deadseascrolls",
    clue: "A shepherd searching for a stray goat stumbles into a cave containing ancient sacred scrolls.",
    name: "Dead Sea Scrolls discovered",
    year: 1947,
    lat: 31.7415,
    lng: 35.4592,
    wikipediaTitle: "Dead_Sea_Scrolls",
    explanation: "A Bedouin shepherd searching for a lost goat discovered ancient Jewish manuscripts in a cave near Qumran, now known as the Dead Sea Scrolls.",
  },
  {
    id: "tereshkova",
    clue: "A former textile worker becomes the first woman to orbit the planet, circling it 48 times from a remote desert launch site.",
    name: "First woman in space launches",
    year: 1963,
    lat: 45.9646,
    lng: 63.3052,
    wikipediaTitle: "Valentina_Tereshkova",
    explanation: "Soviet cosmonaut Valentina Tereshkova became the first woman in space, orbiting Earth 48 times aboard Vostok 6.",
  },
  {
    id: "gandhiassassination",
    clue: "A pacifist leader is shot by an extremist while walking to a prayer meeting at a private estate.",
    name: "Assassination of Mahatma Gandhi",
    year: 1948,
    lat: 28.5933,
    lng: 77.2007,
    wikipediaTitle: "Assassination_of_Mahatma_Gandhi",
    explanation: "Mahatma Gandhi, leader of India's independence movement, was assassinated by a Hindu nationalist in New Delhi.",
  },
  {
    id: "verdun",
    clue: "One of the longest, costliest battles of a world war begins around a fortified river town, inspiring the rallying cry 'they shall not pass.'",
    name: "Battle of Verdun begins",
    year: 1916,
    lat: 49.1586,
    lng: 5.3844,
    wikipediaTitle: "Battle_of_Verdun",
    explanation: "The Battle of Verdun was one of the longest and costliest battles of World War I, fought around the fortified French town of Verdun.",
  },
  {
    id: "cookbotanybay",
    clue: "An explorer's ship anchors in a wide bay after he charts an unmapped eastern coastline, and he claims a vast southern continent for his king.",
    name: "Cook lands at Botany Bay",
    year: 1770,
    lat: -34.0,
    lng: 151.23,
    wikipediaTitle: "James_Cook",
    explanation: "British explorer Captain James Cook landed at Botany Bay, becoming the first European to chart the eastern coast of Australia and claim it for Britain.",
  },
  {
    id: "waitangi",
    clue: "Colonial officials and local chiefs sign a treaty on a lawn overlooking a bay, its two language versions worded to mean different things.",
    name: "Treaty of Waitangi signed",
    year: 1840,
    lat: -35.263,
    lng: 174.077,
    wikipediaTitle: "Treaty_of_Waitangi",
    explanation: "British representatives and Māori chiefs signed the Treaty of Waitangi, establishing British sovereignty over New Zealand.",
  },
  {
    id: "adwa",
    clue: "An independent kingdom's army routs an invading colonial force in the mountains, forcing it to sign a treaty recognizing full sovereignty.",
    name: "Battle of Adwa",
    year: 1896,
    lat: 14.1667,
    lng: 38.9,
    wikipediaTitle: "Battle_of_Adwa",
    explanation: "Ethiopian forces, outnumbering the invading Italian army, decisively defeated it at Adwa, forcing Italy to sign a treaty recognizing Ethiopia's full sovereignty during the European colonial scramble for Africa.",
  },
  {
    id: "maligoldenage",
    clue: "A ruler's famous pilgrimage is so lavish it reportedly crashes gold's price en route, as his fabled capital reaches the height of its golden age.",
    name: "Golden age of Timbuktu",
    year: 1324,
    lat: 16.7666,
    lng: -3.0026,
    wikipediaTitle: "Mansa_Musa",
    explanation: "Under Mansa Musa, the Mali Empire's city of Timbuktu became a renowned center of gold trade and Islamic scholarship, famed after his lavish pilgrimage to Mecca.",
  },
  {
    id: "gritodedolores",
    clue: "A parish priest rings the church bell and calls his parishioners to revolt against colonial rule.",
    name: "Grito de Dolores",
    year: 1810,
    lat: 21.156,
    lng: -100.933,
    wikipediaTitle: "Grito_de_Dolores",
    explanation: "Priest Miguel Hidalgo rang the church bell in the town of Dolores and called for revolt, launching the Mexican War of Independence.",
  },
  {
    id: "haitiindependence",
    clue: "Rebel leaders formally declare the birth of the first free Black republic, born from a slave uprising.",
    name: "Haiti declares independence",
    year: 1804,
    lat: 19.4515,
    lng: -72.6892,
    wikipediaTitle: "Haitian_Declaration_of_Independence",
    explanation: "Haiti declared independence from France, becoming the first nation born from a successful slave revolt.",
  },
  {
    id: "angkorwat",
    clue: "Workers complete a massive temple complex, the largest religious monument the world has ever built.",
    name: "Angkor Wat completed",
    year: 1150,
    lat: 13.4125,
    lng: 103.867,
    wikipediaTitle: "Angkor_Wat",
    explanation: "Angkor Wat, completed under Khmer King Suryavarman II, is the largest religious monument in the world, originally built as a Hindu temple.",
  },
  {
    id: "plassey",
    clue: "A trading company's small army defeats a much larger local ruler after bribing away his own general, opening the door to colonial conquest.",
    name: "Battle of Plassey",
    year: 1757,
    lat: 23.7833,
    lng: 88.25,
    wikipediaTitle: "Battle_of_Plassey",
    explanation: "The British East India Company defeated the Nawab of Bengal at Plassey, a victory that began British colonial rule over India.",
  },
  {
    id: "hijra",
    clue: "A religious leader and his followers migrate to a desert oasis city, marking the start of a new calendar.",
    name: "The Hijra to Medina",
    year: 622,
    lat: 24.4686,
    lng: 39.6142,
    wikipediaTitle: "Hijrah",
    explanation: "The Prophet Muhammad and his followers migrated from Mecca to Medina, an event known as the Hijra that marks the start of the Islamic calendar.",
  },
  {
    id: "tsushima",
    clue: "A modernizing nation's navy annihilates a distant empire's battle fleet in a strait, one of the most lopsided naval victories in modern history.",
    name: "Battle of Tsushima",
    year: 1905,
    lat: 34.2,
    lng: 129.3,
    wikipediaTitle: "Battle_of_Tsushima",
    explanation: "Japan's navy annihilated the Russian fleet at the Battle of Tsushima Strait, a stunning upset that marked Japan's arrival as a modern naval power.",
  },
];

// Keep clues short enough to fit on a couple of lines on mobile.
const MAX_CLUE_LENGTH = 110;
for (const event of POC_EVENTS) {
  if (event.clue.length > MAX_CLUE_LENGTH) {
    console.warn(
      `Clue for "${event.id}" is ${event.clue.length} chars (max ${MAX_CLUE_LENGTH}): "${event.clue}"`
    );
  }
}

export function pickRandomEvents(events: HistoricalEvent[], count: number): HistoricalEvent[] {
  const shuffled = [...events];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}
