// Active pool for the game (v2 guide). Starts empty after the v1 corpus was
// frozen into legacy-events.ts on 2026-09-19 — see docs/event-writing-guide-v2.md.
// Real version would extract this from Wikidata (P585/P580 for date, P625 for coordinates).
import DAILY_PACKS_PLAN from "../../data/daily-packs-plan.json";

export type HistoricalEvent = {
  id: string;
  // true when lat/lng/year point at the subject PERSON's birthplace/birth
  // (map pin = where they were born), not a site/event location. See "Person
  // entries" in docs/event-writing-guide-v2.md: whenever this is true, the
  // clue must contain an explicit birth-signal ("born"/"né"/"naît"). Optional
  // here (legacy-events.ts shares this type and predates the convention);
  // scripts/lint-events.mjs requires it on every entry it actually checks
  // (the active v2 pool), which is where this is really enforced.
  pinIsBirthplace?: boolean;
  // Difficulty as WRITTEN, not inferred from source popularity — see
  // "Writing to a target difficulty" in docs/event-writing-guide-v2.md. The
  // writer picks this before drafting (per current pool-stats.md demand) and
  // applies that tier's hint-generosity rules; it may differ from the
  // candidate pool's pageview-based tag in data/candidates-*.json, which is
  // only a notability floor, not a difficulty assignment. Optional here
  // (legacy-events.ts shares this type and predates the field);
  // scripts/lint-events.mjs requires it on every entry in the active v2 pool.
  difficulty?: "easy" | "medium" | "hard";
  // Theme, chosen at drafting time alongside difficulty — same three keys
  // as TOP_CATEGORIES in scripts/fetch-candidates.mjs (machine-stable keys,
  // not the French display labels). Not used by any pack-assembly logic
  // yet (packs are still a random draw — see pickDailyEvents below), but
  // tagged from the start so nothing needs retagging once that logic
  // exists. Optional here (legacy-events.ts shares this type and predates
  // the field); scripts/lint-events.mjs requires it on every entry in the
  // active v2 pool.
  category?: "conflict_politics_society" | "arts_culture" | "science_infrastructure";
  clue: string;
  name: string;
  explanation: string;
  year: number; // negative = BCE
  lat: number;
  lng: number;
  wikipediaTitle: string;
};

export const POC_EVENTS: HistoricalEvent[] = [
  {
    id: "great_pyramid_giza",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Along the Nile, a giant pyramid built as a king's tomb stayed the tallest structure on Earth for over 3,800 years.",
    name: "Great Pyramid of Giza",
    explanation: "The Great Pyramid of Giza was built as the tomb of the pharaoh Khufu, using more than two million limestone blocks. It is the only one of the Seven Wonders of the Ancient World still standing today.",
    year: -2561,
    lat: 29.97915,
    lng: 31.13422,
    wikipediaTitle: "Great_Pyramid_of_Giza",
  },
  {
    id: "machu_picchu",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "High in the mountains above the Urubamba River, an empire without wheeled vehicles carved a stone citadel into a steep ridge above a winding canyon.",
    name: "Machu Picchu",
    explanation: "Machu Picchu was built by the Inca Empire as a royal estate, then abandoned and largely forgotten by outsiders until its rediscovery drew worldwide attention.",
    year: 1450,
    lat: -13.163333,
    lng: -72.545556,
    wikipediaTitle: "Machu_Picchu",
  },
  {
    id: "angkor_wat",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Near Tonlé Sap, the largest religious monument on Earth was built as a temple honoring a Hindu god, surrounded by a wide moat shaped like a giant rectangle.",
    name: "Angkor Wat",
    explanation: "Angkor Wat was built as a Hindu temple dedicated to Vishnu before gradually becoming a Buddhist site. It still appears on Cambodia's national flag today.",
    year: 1200,
    lat: 13.4125,
    lng: 103.866667,
    wikipediaTitle: "Angkor_Wat",
  },
  {
    id: "christ_the_redeemer",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "On a mountaintop overlooking a bay, a giant statue of a religious figure stands with its arms spread wide over the city below.",
    name: "Christ the Redeemer",
    explanation: "Christ the Redeemer is a statue of Jesus, built with a French engineer's help and finished with a face carved by a Romanian sculptor. Its arms stretch nearly 30 meters wide.",
    year: 1920,
    lat: -22.951916,
    lng: -43.210464,
    wikipediaTitle: "Christ_the_Redeemer_(statue)",
  },
  {
    id: "tohoku_earthquake_tsunami",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Off the coast of Tōhoku, a huge undersea earthquake triggered a tsunami that struck the shoreline and knocked out a nuclear plant's cooling systems.",
    name: "Tōhoku earthquake and tsunami",
    explanation: "The Tōhoku earthquake was one of the most powerful ever recorded by modern instruments. The resulting tsunami caused a meltdown at the Fukushima Daiichi nuclear plant.",
    year: 2011,
    lat: 38.322,
    lng: 142.369,
    wikipediaTitle: "2011_Tōhoku_earthquake_and_tsunami",
  },
  {
    id: "woodstock_festival",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "On a dairy farm in the Catskill Mountains, half a million people gathered for three days of music after heavy rain turned the fields into deep mud.",
    name: "Woodstock",
    explanation: "Woodstock was billed as three days of peace and music. Despite overcast skies and repeated rain, dozens of acts performed outdoors for a crowd far bigger than organizers expected.",
    year: 1969,
    lat: 41.7,
    lng: -74.88,
    wikipediaTitle: "Woodstock",
  },
  {
    id: "oktoberfest_munich",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "The world's largest beer festival began as a wedding celebration for a crown prince, and now fills giant tents with visitors every year.",
    name: "Oktoberfest",
    explanation: "Oktoberfest started as a public celebration of a royal wedding and grew into an annual folk festival combining beer tents with fairground rides.",
    year: 1810,
    lat: 48.131389,
    lng: 11.549167,
    wikipediaTitle: "Oktoberfest",
  },
  {
    id: "first_modern_olympics",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "The first modern Olympic Games brought together athletes from several nations to compete at the same stadium where the ancient games once took place.",
    name: "First Modern Olympics",
    explanation: "The Games were revived by a French aristocrat who championed international athletic competition. They were held in a marble stadium built for the occasion, reviving a tradition from antiquity.",
    year: 1896,
    lat: 37.984167,
    lng: 23.728056,
    wikipediaTitle: "1896_Summer_Olympics",
  },
  {
    id: "battle_of_waterloo",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "A defeated emperor fought his final battle in the countryside as coalition armies converged on him from several directions at once.",
    name: "Battle of Waterloo",
    explanation: "Napoleon's defeat at Waterloo ended his rule for good and forced him into exile on a remote island for the rest of his life.",
    year: 1815,
    lat: 50.678056,
    lng: 4.412222,
    wikipediaTitle: "Battle_of_Waterloo",
  },
  {
    id: "october_revolution_petrograd",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "In the capital of a vast empire, revolutionaries stormed a royal palace at night, toppling the government and founding the world's first communist state.",
    name: "October Revolution",
    explanation: "The uprising in Petrograd was led by Lenin's Bolsheviks and triggered a long civil war across the country before their new government secured full control.",
    year: 1917,
    lat: 59.95,
    lng: 30.316667,
    wikipediaTitle: "October_Revolution",
  },
  {
    id: "fall_of_constantinople",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "A huge army laid siege to a fortified capital for 53 days, breaching its walls with massive cannons and ending a thousand-year-old empire.",
    name: "Fall of Constantinople",
    explanation: "The 53-day siege ended the Byzantine Empire and turned its capital into the new center of the Ottoman Empire. Enormous bronze cannons breached walls that had stood for over a thousand years.",
    year: 1453,
    lat: 41.03,
    lng: 28.935,
    wikipediaTitle: "Fall_of_Constantinople",
  },
  {
    id: "battle_of_hastings",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "An invading army that crossed the sea defeated the reigning king in a single day of fighting, putting a new royal dynasty on the throne.",
    name: "Battle of Hastings",
    explanation: "The invading duke's victory at Hastings began a new ruling dynasty, and the battle was later commemorated in a nearly 70-meter-long embroidered tapestry.",
    year: 1066,
    lat: 50.911945,
    lng: 0.4875,
    wikipediaTitle: "Battle_of_Hastings",
  },
  {
    id: "colosseum",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "An enormous stone arena once held tens of thousands of spectators watching gladiators fight for their lives in front of a roaring crowd.",
    name: "Colosseum",
    explanation: "The Colosseum was built under three emperors of the same family and could stage mock sea battles by flooding its arena floor with water.",
    year: 82,
    lat: 41.890278,
    lng: 12.492222,
    wikipediaTitle: "Colosseum",
  },
  {
    id: "petra_jordan",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "An ancient city was carved directly into rose-colored sandstone cliffs, its main entrance hidden inside a narrow winding canyon.",
    name: "Petra",
    explanation: "Petra served as the capital of the Nabataean kingdom and thrived by controlling caravan trade routes. It has an elaborate system of channels and cisterns that once brought water into the desert city.",
    year: -801,
    lat: 30.328889,
    lng: 35.440278,
    wikipediaTitle: "Petra",
  },
  {
    id: "normandy_landings",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "Thousands of ships landed troops on five beaches at dawn in what remains the largest seaborne invasion ever launched.",
    name: "Normandy Landings",
    explanation: "The landings opened a new front against Nazi-occupied territory and marked the beginning of the liberation of Western Europe.",
    year: 1944,
    lat: 49.34,
    lng: -0.6,
    wikipediaTitle: "Normandy_landings",
  },
  {
    id: "battle_of_austerlitz",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "An emperor's outnumbered army lured two larger allied forces into a trap and won a battle later nicknamed the clash of three emperors.",
    name: "Battle of Austerlitz",
    explanation: "Napoleon's victory at Austerlitz effectively destroyed the Third Coalition and is often considered the greatest tactical victory of his career.",
    year: 1805,
    lat: 49.128056,
    lng: 16.7625,
    wikipediaTitle: "Battle_of_Austerlitz",
  },
  {
    id: "olympic_flame_debut",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "In a city famous for its canals, the Olympic Games lit a continuously burning flame for the first time, a tradition continued at every edition since.",
    name: "Olympic Flame Debut",
    explanation: "The Amsterdam Olympics also allowed female athletes to compete in track and field events for the first time.",
    year: 1928,
    lat: 52.366667,
    lng: 4.883333,
    wikipediaTitle: "1928_Summer_Olympics",
  },
  {
    id: "nikola_tesla_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "Born during a storm in a mountain village, he built the alternating-current system powering homes worldwide, feuding with a rival who backed direct current.",
    name: "Nikola Tesla",
    explanation: "Nikola Tesla was born in the village of Smiljan. His feud with Thomas Edison over AC versus DC power became known as the War of Currents.",
    year: 1856,
    lat: 44.5643,
    lng: 15.3181,
    wikipediaTitle: "Nikola_Tesla",
  },
  {
    id: "indian_ocean_tsunami",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "In a warm, tropical sea, a massive undersea earthquake triggered a tsunami that killed hundreds of thousands of people across several countries at once.",
    name: "Indian Ocean Tsunami",
    explanation: "The earthquake struck off the coast of Sumatra and generated waves that struck coastlines across the Indian Ocean within hours, catching most coastal communities completely by surprise.",
    year: 2004,
    lat: 3.295,
    lng: 95.982,
    wikipediaTitle: "2004_Indian_Ocean_earthquake_and_tsunami",
  },
  {
    id: "battle_of_thermopylae",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a narrow mountain pass between steep cliffs and the sea, a small defending force held off a much larger army for three days before being overwhelmed.",
    name: "Battle of Thermopylae",
    explanation: "A force led by Spartan king Leonidas blocked the pass until a local shepherd showed the invaders a hidden path around it, allowing them to attack from behind.",
    year: -480,
    lat: 38.795833,
    lng: 22.536945,
    wikipediaTitle: "Battle_of_Thermopylae",
  },
  {
    id: "spitak_earthquake",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "A powerful earthquake leveled entire towns in under a minute, killing tens of thousands and pushing rival superpowers to cooperate despite deep tension.",
    name: "Spitak Earthquake",
    explanation: "The earthquake struck northern Armenia and led to an unusual moment of diplomatic cooperation between rival global powers, despite ongoing political tension between them.",
    year: 1988,
    lat: 40.983333,
    lng: 44.183333,
    wikipediaTitle: "1988_Armenian_earthquake",
  },
  {
    id: "klondike_gold_rush",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "Word of a huge gold discovery in a remote wilderness sent tens of thousands of prospectors rushing north in one year, many giving up everything for the trip.",
    name: "Klondike Gold Rush",
    explanation: "Most prospectors who reached the Klondike region found the best claims already taken, and only a small fraction of those who set out ever struck it rich.",
    year: 1896,
    lat: 64.034917,
    lng: -139.285961,
    wikipediaTitle: "Klondike_Gold_Rush",
  },
  {
    id: "chichen_itza",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "On the Yucatán Peninsula, an ancient civilization built a pyramid so aligned that twice a year, its stairs cast a shadow shaped like a slithering serpent.",
    name: "Chichen Itza",
    explanation: "The pyramid, known as El Castillo, was built by the Maya as a temple to the feathered serpent god Kukulcan. Its 365 steps match the days of the solar year.",
    year: 455,
    lat: 20.683056,
    lng: -88.568611,
    wikipediaTitle: "Chichen_Itza",
  },
  {
    id: "babylon_hanging_gardens",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "On the banks of the Euphrates, an ancient city became famous for hanging gardens ancient writers counted among the wonders of the world.",
    name: "Babylon",
    explanation: "Babylon's hanging gardens, if they existed as described, would have been one of the Seven Wonders of the Ancient World, though no definitive archaeological trace of them has ever been found.",
    year: -1895,
    lat: 32.5425,
    lng: 44.421111,
    wikipediaTitle: "Babylon",
  },
  {
    id: "persepolis",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Encircled by the Zagros Mountains, a ceremonial capital was built with staircases carved with soldiers and tribute-bearers, before being burned by a conqueror.",
    name: "Persepolis",
    explanation: "Persepolis served as the ceremonial capital of the Achaemenid Persian Empire. It was burned during Alexander the Great's conquest, though historians still debate whether it was deliberate or accidental.",
    year: -511,
    lat: 29.935,
    lng: 52.89,
    wikipediaTitle: "Persepolis",
  },
  {
    id: "terracotta_army",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Thousands of life-sized clay soldiers were buried to guard an emperor's tomb, each sculpted with a distinct face so no two look alike.",
    name: "Terracotta Army",
    explanation: "The figures were built for the tomb of Qin Shi Huang, China's first emperor, and were rediscovered by farmers digging a well, completely by accident.",
    year: -249,
    lat: 34.385,
    lng: 109.273055,
    wikipediaTitle: "Terracotta_Army",
  },
  {
    id: "borobudur_temple",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "On a volcanic island near the equator, the world's largest Buddhist monument is a stone mandala, climbed level by level as a journey toward enlightenment.",
    name: "Borobudur",
    explanation: "Borobudur was abandoned for centuries, buried under volcanic ash and jungle growth, before being rediscovered and painstakingly restored.",
    year: 800,
    lat: -7.60793,
    lng: 110.20384,
    wikipediaTitle: "Borobudur",
  },
  {
    id: "stockholm_1912_olympics",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "In a city built across a scattering of islands, the Olympic Games used electric timing and telegraphs to report results, replacing stopwatches and messengers.",
    name: "Stockholm Olympic Games",
    explanation: "The Stockholm Games were also the first to feature athletes from all five inhabited continents competing together.",
    year: 1912,
    lat: 59.329444,
    lng: 18.068611,
    wikipediaTitle: "1912_Summer_Olympics",
  },
  {
    id: "melbourne_1956_olympics",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "The Olympic Games were held in local summer while the rest of the world sat in winter, the first Olympics hosted in the Southern Hemisphere.",
    name: "Melbourne Olympic Games",
    explanation: "Because horses faced a lengthy quarantine to enter the country, the equestrian events for these Games were held on the other side of the world, months earlier.",
    year: 1956,
    lat: -37.814167,
    lng: 144.963056,
    wikipediaTitle: "1956_Summer_Olympics",
  },
  {
    id: "euromaidan",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "Along the Dnieper River, months of protests in a central square forced out the sitting president after a violent crackdown turned opinion against him.",
    name: "Euromaidan",
    explanation: "The protests began after the president rejected a trade agreement with the European Union in favor of closer ties with Russia, and grew into the largest pro-democracy movement in Europe in decades.",
    year: 2013,
    lat: 50.45025,
    lng: 30.52389,
    wikipediaTitle: "Euromaidan",
  },
  {
    id: "leonardo_da_vinci_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a small hill town surrounded by vineyards, he later painted the single most recognized portrait in the world.",
    name: "Leonardo da Vinci",
    explanation: "Leonardo da Vinci was born in the town of Vinci, the illegitimate son of a notary. The portrait, the Mona Lisa, still hangs behind bulletproof glass in a Paris museum.",
    year: 1452,
    lat: 43.799167,
    lng: 10.938133,
    wikipediaTitle: "Leonardo_da_Vinci",
  },
  {
    id: "battle_of_grunwald",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a forested plain near a small lake, an allied coalition crushed a powerful military order, killing its supreme commander in one of the era's largest battles.",
    name: "Battle of Grunwald",
    explanation: "The battle pitted the Kingdom of Poland and the Grand Duchy of Lithuania against the Teutonic Knights, whose leadership was largely killed or captured.",
    year: 1410,
    lat: 53.486111,
    lng: 20.124722,
    wikipediaTitle: "Battle_of_Grunwald",
  },
  {
    id: "battle_of_badr",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a desert valley beside a strategic well, a small band of the newly faithful defeated a larger force in a battle marking a turning point for a new religion.",
    name: "Battle of Badr",
    explanation: "The Battle of Badr pitted a small group of early Muslims led by Muhammad against a larger force from Mecca, and is regarded as a foundational event in early Islamic history.",
    year: 624,
    lat: 23.733333,
    lng: 38.766667,
    wikipediaTitle: "Battle_of_Badr",
  },
  {
    id: "haiti_earthquake",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "On a mountainous island shared by two nations, a powerful earthquake devastated a packed capital in under a minute, killing more than a hundred thousand people.",
    name: "Haiti Earthquake",
    explanation: "The earthquake struck Haiti, one of two countries sharing the island of Hispaniola, and was among the deadliest disasters ever recorded relative to the size of the country's population.",
    year: 2010,
    lat: 18.451389,
    lng: -72.445194,
    wikipediaTitle: "2010_Haiti_earthquake",
  },
  {
    id: "paris_world_fair_1889",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "arts_culture",
    clue: "A world's fair featured a towering iron structure built as a temporary centerpiece, planned for demolition after twenty years but kept for scientific use.",
    name: "Paris World's Fair",
    explanation: "The tower was built for the Paris World's Fair by engineer Gustave Eiffel and became the tallest man-made structure in the world at the time. It survived demolition because the military found a practical use for it as a communications antenna.",
    year: 1889,
    lat: 48.858333,
    lng: 2.294167,
    wikipediaTitle: "Exposition_Universelle_(1889)",
  },
  {
    id: "iron_pillar_delhi",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "A solid metal pillar taller than a two-story building has stood outdoors for over a thousand years without rusting, fascinating the metallurgists who study it.",
    name: "Iron Pillar of Delhi",
    explanation: "Scientists believe a thin protective layer formed by the iron's unusual phosphorus content is what has kept the pillar from rusting away for so long.",
    year: 500,
    lat: 28.524656,
    lng: 77.185069,
    wikipediaTitle: "Iron_pillar_of_Delhi",
  },
  {
    id: "svalbard_treaty",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "A treaty granted one nation sovereignty over a remote island territory while guaranteeing other signing countries equal rights to mine and fish there.",
    name: "Svalbard Treaty",
    explanation: "The Svalbard Treaty gave Norway sovereignty over the Arctic archipelago while allowing other signatories, including Russia, to maintain settlements and mining operations there.",
    year: 1920,
    lat: 78.2232,
    lng: 15.6267,
    wikipediaTitle: "Svalbard_Treaty",
  },
  {
    id: "bagan",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Along the Irrawaddy River, an ancient kingdom built more than ten thousand Buddhist temples and pagodas across a plain, thousands of which still stand today.",
    name: "Bagan",
    explanation: "Bagan was the capital of the Pagan Kingdom, the first kingdom to unify the region that later became Myanmar. Many of its temples remain active pilgrimage sites.",
    year: 200,
    lat: 21.1725,
    lng: 94.86,
    wikipediaTitle: "Bagan",
  },
  {
    id: "cave_of_altamira",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "In the Cantabrian Mountains, a cave hidden for millennia contains painted bison and horses so skillful that experts first refused to believe they were ancient.",
    name: "Cave of Altamira",
    explanation: "The paintings at Altamira were eventually confirmed to be tens of thousands of years old, made using charcoal and natural pigments blown or dabbed onto the rock.",
    year: -1301,
    lat: 43.376944,
    lng: -4.11975,
    wikipediaTitle: "Cave_of_Altamira",
  },
  {
    id: "nepal_earthquake",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "In the Himalayas, a massive earthquake triggered deadly avalanches on the world's tallest mountain, killing climbers at base camp and devastating towns nearby.",
    name: "Nepal Earthquake",
    explanation: "The earthquake was the deadliest disaster to strike Nepal in decades and also triggered a major avalanche on Mount Everest that killed climbers and Sherpa guides at base camp.",
    year: 2015,
    lat: 28.165,
    lng: 84.725,
    wikipediaTitle: "April_2015_Nepal_earthquake",
  },
  {
    id: "helsinki_1952_olympics",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "On the Baltic coast, the Olympic Games saw a Cold War rival compete for the first time in decades, the medal count becoming a symbol of superpower rivalry.",
    name: "Helsinki Olympic Games",
    explanation: "The Helsinki Games also featured long-distance runner Emil Zátopek winning three gold medals, including a marathon he had never raced before.",
    year: 1952,
    lat: 60.170833,
    lng: 24.9375,
    wikipediaTitle: "1952_Summer_Olympics",
  },
  {
    id: "montreal_1976_olympics",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "arts_culture",
    clue: "On an island in the Saint Lawrence River, a fourteen-year-old gymnast scored the Olympics' first perfect ten, a score too unexpected for the board to display.",
    name: "Montreal Olympic Games",
    explanation: "Romanian gymnast Nadia Comaneci earned the historic score on the uneven bars, and went on to receive six more perfect tens during the same Games.",
    year: 1976,
    lat: 45.55781,
    lng: -73.55164,
    wikipediaTitle: "1976_Summer_Olympics",
  },
  {
    id: "schengen_agreement",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "On the Moselle River, five nations signed a treaty aboard a boat that abolished passport checks at their borders, creating a huge free-travel zone.",
    name: "Schengen Agreement",
    explanation: "The agreement was signed near the village of Schengen and eventually grew to cover most of the European Union, letting travelers cross many borders without ever showing a passport.",
    year: 1985,
    lat: 49.47,
    lng: 6.36,
    wikipediaTitle: "Schengen_Agreement",
  },
  {
    id: "mozart_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a small mountain town known for its salt mines, this musical prodigy was already composing symphonies before he became a teenager.",
    name: "Wolfgang Amadeus Mozart",
    explanation: "Wolfgang Amadeus Mozart was born in Salzburg. He completed more than 800 works in his short life and is regarded as one of the greatest composers in Western music.",
    year: 1756,
    lat: 47.8,
    lng: 13.045,
    wikipediaTitle: "Wolfgang_Amadeus_Mozart",
  },
  {
    id: "van_gogh_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a village parsonage in flat farming country, this painter became famous for a swirling night sky full of stars, painted during a stay in an asylum.",
    name: "Vincent van Gogh",
    explanation: "Vincent van Gogh was born in the village of Groot-Zundert, the son of a Protestant minister. He sold only a handful of paintings in his lifetime but is now among the most recognized artists in history.",
    year: 1853,
    lat: 51.4703,
    lng: 4.66,
    wikipediaTitle: "Vincent_van_Gogh",
  },
  {
    id: "battle_of_marathon",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "On a coastal plain hemmed in by hills and the sea, outnumbered defenders routed an invading force, and a messenger's run afterward inspired a modern race.",
    name: "Battle of Marathon",
    explanation: "The victory at Marathon was won by Athenian and allied forces against a much larger Persian invasion fleet, and is often seen as a foundational moment for early Greek democracy's confidence.",
    year: -490,
    lat: 38.118056,
    lng: 23.978333,
    wikipediaTitle: "Battle_of_Marathon",
  },
  {
    id: "battle_of_cannae",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "On a dry plain beside a river, a brilliant double-pincer maneuver by an outnumbered army encircled and annihilated a much larger enemy force in a single day.",
    name: "Battle of Cannae",
    explanation: "The tactic at Cannae was devised by the Carthaginian general Hannibal against Rome, and the battle is still studied in military academies today as a model of tactical envelopment.",
    year: -216,
    lat: 41.306389,
    lng: 16.1325,
    wikipediaTitle: "Battle_of_Cannae",
  },
  {
    id: "byblos_lebanon",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "On a coastal hillside beside a warm sea, one of the world's oldest inhabited cities lent its name, through ancient traders, to the modern word for 'book'.",
    name: "Byblos",
    explanation: "Byblos was a major Phoenician port that exported papyrus to Greece, and the Greek word for the city, byblos, is the root of words like 'Bible' and 'bibliography'.",
    year: -8001,
    lat: 34.116667,
    lng: 35.65,
    wikipediaTitle: "Byblos",
  },
  {
    id: "montreal_protocol",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "A global treaty phased out chemicals destroying a protective layer high in the atmosphere, called one of the most successful environmental agreements signed.",
    name: "Montreal Protocol",
    explanation: "The Montreal Protocol targeted chlorofluorocarbons that were widening a hole in the ozone layer above Antarctica, and the ozone layer has been steadily recovering since it took effect.",
    year: 1987,
    lat: 45.503343,
    lng: -73.586841,
    wikipediaTitle: "Montreal_Protocol",
  },
  {
    id: "locarno_treaties",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "A set of treaties had former wartime enemies mutually guarantee their shared borders, though the diplomatic optimism it created collapsed within a decade.",
    name: "Locarno Treaties",
    explanation: "The Locarno Treaties guaranteed the postwar borders between Germany, France, and Belgium, and were seen as a diplomatic triumph before later collapsing as tensions rose again.",
    year: 1925,
    lat: 46.166389,
    lng: 8.799722,
    wikipediaTitle: "Locarno_Treaties",
  },
  {
    id: "union_of_utrecht",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "A group of newly Protestant provinces united against a distant Catholic king's harsh rule and religious persecution, founding a nation decades later.",
    name: "Union of Utrecht",
    explanation: "The Union of Utrecht bound several Dutch provinces together against Spanish rule and is regarded as an early precursor to the modern constitution of the Netherlands.",
    year: 1579,
    lat: 52.0908,
    lng: 5.1217,
    wikipediaTitle: "Union_of_Utrecht",
  },
  {
    id: "ggantija_malta",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "On a small island, a temple built from massive stone blocks is one of the oldest free-standing structures built, predating the first pyramids by a millennium.",
    name: "Ġgantija Temples",
    explanation: "The Ġgantija temples on the island of Gozo are among the Megalithic Temples of Malta, and are believed to be the second-oldest known man-made religious structures in the world.",
    year: -3600,
    lat: 36.047265,
    lng: 14.269095,
    wikipediaTitle: "Ġgantija",
  },
  {
    id: "shakespeare_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a small market town on a slow river amid flat farmland, this playwright introduced hundreds of new words that are still used in everyday speech today.",
    name: "William Shakespeare",
    explanation: "William Shakespeare was born in Stratford-upon-Avon, the son of a glove maker. His 39 plays and more than 150 sonnets have been translated into dozens of languages and are still performed more than any other playwright's work.",
    year: 1564,
    lat: 52.192778,
    lng: -1.706389,
    wikipediaTitle: "William_Shakespeare",
  },
  {
    id: "confucius_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a small town on a broad farming plain, this philosopher spent years pitching his ideas on government to rival rulers who mostly ignored him.",
    name: "Confucius",
    explanation: "Confucius was born near the town of Qufu on the North China Plain. His teachings on ethics and social harmony were largely ignored during his own lifetime but were later adopted as the guiding philosophy for education and government across the region for centuries.",
    year: -551,
    lat: 35.6,
    lng: 116.983333,
    wikipediaTitle: "Confucius",
  },
  {
    id: "basho_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born in a small town ringed by mountains, this poet perfected a seventeen-syllable verse form and walked thousands of kilometers to write a famous travel diary.",
    name: "Matsuo Bashō",
    explanation: "Matsuo Bashō was born in the town of Ueno. His travel account blending prose and haiku describes a journey on foot through remote countryside, and he died on the road during a later journey.",
    year: 1644,
    lat: 34.768621,
    lng: 136.135453,
    wikipediaTitle: "Matsuo_Bashō",
  },
  {
    id: "cervantes_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "arts_culture",
    clue: "Born on a dry inland plain, this novelist was maimed in a naval battle, then enslaved by pirates for years before writing the first modern novel.",
    name: "Miguel de Cervantes",
    explanation: "Miguel de Cervantes was born in Alcalá de Henares. Wounded and maimed in a major naval battle, he was later captured at sea and held captive for years before being ransomed. His novel Don Quixote is often cited as the first modern novel.",
    year: 1547,
    lat: 40.481815,
    lng: -3.364305,
    wikipediaTitle: "Miguel_de_Cervantes",
  },
  {
    id: "cannes_film_festival",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "arts_culture",
    clue: "In a resort town on a warm southern coastline, the world's top film festival awards its prize each year as a stylized golden palm frond, not a trophy or medal.",
    name: "Cannes Film Festival",
    explanation: "The Cannes Film Festival is held each year in a converted casino town on the coast. Its top prize, the Palme d'Or, has been awarded in the shape of a stylized gold palm frond since the award began.",
    year: 1946,
    lat: 43.550833,
    lng: 7.018056,
    wikipediaTitle: "Cannes_Film_Festival",
  },
  {
    id: "potsdam_conference",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "At a lakeside palace near a ruined capital, the winning nations met to decide a defeated country's fate; one leader lost office mid-summit after an election.",
    name: "Potsdam Conference",
    explanation: "The Potsdam Conference brought together leaders of the war's three victorious powers to decide how to administer Germany after its surrender. Partway through, the British delegation's leader changed when Winston Churchill's party lost a general election back home, and Clement Attlee took his place.",
    year: 1945,
    lat: 52.419169,
    lng: 13.070831,
    wikipediaTitle: "Potsdam_Conference",
  },
  {
    id: "council_of_trent",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a city ringed by steep, snow-capped peaks, a religious council met on and off for eighteen years, reaffirming doctrine amid a growing religious schism.",
    name: "Council of Trent",
    explanation: "The Council of Trent was convened in the city of Trent, now Trento in northern Italy, in response to a growing religious schism within the church. Its sessions were repeatedly interrupted by war, plague, and political disputes, stretching a process expected to take months into nearly two decades.",
    year: 1545,
    lat: 44.493889,
    lng: 11.342778,
    wikipediaTitle: "Council_of_Trent",
  },
  {
    id: "second_council_of_nicaea",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a walled town beside a lake, a religious council overturned decades of bans on religious images, ending a dispute that had split the church for a generation.",
    name: "Second Council of Nicaea",
    explanation: "The council met in the town now known as İznik, on the shore of a lake in northwestern Anatolia. It restored the veneration of religious icons after decades of imperial bans on, and destruction of, religious images.",
    year: 787,
    lat: 40.4292,
    lng: 29.72017,
    wikipediaTitle: "Second_Council_of_Nicaea",
  },
  {
    id: "battle_of_dien_bien_phu",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "In a remote valley ringed by forested hills, a fortified army was besieged after its enemy hauled heavy artillery up the slopes and dug it into the hillsides.",
    name: "Battle of Dien Bien Phu",
    explanation: "At Dien Bien Phu, Viet Minh forces hauled heavy artillery piece by piece up steep jungle slopes and dug the guns into camouflaged positions overlooking the French base below. The resulting siege ended in a decisive defeat that led to the end of French colonial rule in the region.",
    year: 1954,
    lat: 21.386944,
    lng: 103.015556,
    wikipediaTitle: "Battle_of_Dien_Bien_Phu",
  },
  {
    id: "bretton_woods_system",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "conflict_politics_society",
    clue: "At a grand hotel below the tallest peak in a mountain range, delegates from dozens of nations agreed to tie their currencies to gold through a single one.",
    name: "Bretton Woods system",
    explanation: "Delegates from 44 countries met at the Mount Washington Hotel to design a new global monetary system after the war, pegging currencies to the US dollar, which was itself convertible to gold. The agreement also created the International Monetary Fund and the World Bank.",
    year: 1944,
    lat: 44.25436,
    lng: -71.44787,
    wikipediaTitle: "Bretton_Woods_system",
  },
  {
    id: "newton_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "Born so premature he wasn't expected to survive, in a rural manor on flat farmland, he worked out gravity's laws after an apple fell during a plague outbreak.",
    name: "Isaac Newton",
    explanation: "Isaac Newton was born at Woolsthorpe Manor, two months premature and so small his mother said he could fit inside a quart mug. He developed his theory of gravity partly while isolated at home when a plague outbreak closed the university he attended.",
    year: 1643,
    lat: 52.809167,
    lng: -0.630556,
    wikipediaTitle: "Isaac_Newton",
  },
  {
    id: "ibn_battuta_birth",
    pinIsBirthplace: true,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "Born in a coastal city where a narrow strait meets the ocean, this traveler covered some 120,000 kilometers over three decades, farther than any prior explorer.",
    name: "Ibn Battuta",
    explanation: "Ibn Battuta was born in Tangier. Setting out on a pilgrimage in his twenties, he kept traveling for nearly thirty years, crossing North and West Africa, the Middle East, Central and South Asia, and China, later dictating an account of his journeys known as the Rihla.",
    year: 1304,
    lat: 35.76963,
    lng: -5.803352,
    wikipediaTitle: "Ibn_Battuta",
  },
  {
    id: "nazca_lines",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "On a high, bone-dry desert plateau, an ancient culture carved giant lines and animal shapes so large they're only fully recognizable from the air.",
    name: "Nazca Lines",
    explanation: "The Nazca Lines were made by scraping away dark surface stones to reveal lighter soil beneath, forming shapes including a hummingbird, a monkey, and a spider. Because the desert here gets almost no rain or wind, many of the lines have survived largely undisturbed for well over a thousand years.",
    year: -200,
    lat: -14.6975,
    lng: -75.135,
    wikipediaTitle: "Nazca_lines",
  },
  {
    id: "ur_mesopotamia",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "Near a river's mouth, this ancient city, tied to a biblical patriarch's birth, grew for millennia before its coastline shifted, stranding its ruins far inland.",
    name: "Ur",
    explanation: "Ur grew from an early settlement into a major Sumerian city-state in ancient Mesopotamia, and is traditionally identified in the Hebrew Bible as the birthplace of the patriarch Abraham. The Euphrates has since shifted course, and the site, once a bustling port, now sits well inland in southern Iraq.",
    year: -3801,
    lat: 30.962222,
    lng: 46.104444,
    wikipediaTitle: "Ur",
  },
  {
    id: "charminar",
    pinIsBirthplace: false,
    difficulty: "medium",
    category: "science_infrastructure",
    clue: "On a high inland plateau, a ruler built a monument with four towering minarets to mark the end of a devastating plague epidemic that had swept through his city.",
    name: "Charminar",
    explanation: "The Charminar was built in Hyderabad by a local ruler, reportedly to commemorate the end of a plague epidemic and to mark the founding of a new city. Its four minarets remain the city's best-known landmark, and it stood as the tallest structure in the city for roughly four centuries.",
    year: 1591,
    lat: 17.361607,
    lng: 78.474657,
    wikipediaTitle: "Charminar",
  },
  {
    id: "du_fu_birth",
    pinIsBirthplace: true,
    difficulty: "hard",
    category: "arts_culture",
    clue: "Born near a bend in a great river, this poet wrote nearly 1,500 surviving poems, dying poor before being hailed as one of his country's greatest writers.",
    name: "Du Fu",
    explanation: "Du Fu was born near Gongxian, close to the Yellow River. Though barely recognized in his own time, his nearly 1,500 surviving poems later earned him a reputation as one of the greatest poets in his language's history.",
    year: 712,
    lat: 34.75128,
    lng: 112.98541,
    wikipediaTitle: "Du_Fu",
  },
  {
    id: "abu_nuwas_birth",
    pinIsBirthplace: true,
    difficulty: "hard",
    category: "arts_culture",
    clue: "Born on a hot lowland plain, this poet turned scandalous verses about wine into celebrated literature, later becoming a trickster in a famous story collection.",
    name: "Abu Nuwas",
    explanation: "Abu Nuwas was born in Ahvaz. His witty, often scandalous poetry celebrating wine and pleasure broke sharply from older desert-themed traditions, and he later appears as a trickster figure in One Thousand and One Nights.",
    year: 762,
    lat: 31.318889,
    lng: 48.684167,
    wikipediaTitle: "Abu_Nuwas",
  },
  {
    id: "la_fontaine_birth",
    pinIsBirthplace: true,
    difficulty: "hard",
    category: "arts_culture",
    clue: "Born near a river, this poet stayed loyal to his patron after the man's fall and imprisonment, still writing fables schoolchildren memorize today.",
    name: "Jean de La Fontaine",
    explanation: "Jean de La Fontaine was born in Château-Thierry. When his patron, a powerful finance minister, was arrested on corruption charges, La Fontaine risked royal anger by publicly pleading for his release. His Fables, featuring talking animals standing in for human vices and virtues, became a model imitated by fable writers across the continent.",
    year: 1621,
    lat: 49.046389,
    lng: 3.403056,
    wikipediaTitle: "Jean_de_La_Fontaine",
  },
  {
    id: "bunin_birth",
    pinIsBirthplace: true,
    difficulty: "hard",
    category: "arts_culture",
    clue: "Born on a broad inland plain, this writer became the first from his language to win a Nobel Prize for literature, penning his best work while exiled abroad.",
    name: "Ivan Bunin",
    explanation: "Ivan Bunin was born near Voronezh. After leaving his homeland following political upheaval, he settled abroad and wrote much of his best-known fiction in exile, before winning his Nobel Prize.",
    year: 1870,
    lat: 51.671667,
    lng: 39.210556,
    wikipediaTitle: "Ivan_Bunin",
  },
  {
    id: "masaccio_birth",
    pinIsBirthplace: true,
    difficulty: "hard",
    category: "arts_culture",
    clue: "Born in a small hill town, this painter mastered lifelike perspective and shadow, then died suddenly at twenty-six, having already reshaped painting for good.",
    name: "Masaccio",
    explanation: "Masaccio was born in San Giovanni Valdarno. His mastery of perspective and naturalistic light made his small surviving body of frescoes hugely influential on the painters who followed, though he died suddenly while still in his twenties.",
    year: 1401,
    lat: 43.564444,
    lng: 11.532778,
    wikipediaTitle: "Masaccio",
  },
  {
    id: "treaty_of_pyrenees",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "On a tiny island in a border river, two kingdoms ended a long war with a treaty; the island's rule still alternates between both countries every six months.",
    name: "Treaty of the Pyrenees",
    explanation: "The Treaty of the Pyrenees ended a long war between France and Spain and was negotiated on Pheasant Island, a small island in the Bidasoa River. The island's sovereignty has alternated between the two countries every six months ever since, an arrangement still honored today.",
    year: 1659,
    lat: 43.342778,
    lng: -1.7655,
    wikipediaTitle: "Treaty_of_the_Pyrenees",
  },
  {
    id: "austrian_state_treaty",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "In a palace in a divided, occupied capital, four wartime allies restored the country's full sovereignty, on condition it declare permanent neutrality.",
    name: "Austrian State Treaty",
    explanation: "The Austrian State Treaty was signed at the Belvedere Palace in Vienna. It ended a decade of four-power occupation and restored full Austrian sovereignty, on the condition that the country adopt permanent neutrality, a status it maintains to this day.",
    year: 1955,
    lat: 48.1934,
    lng: 16.380519,
    wikipediaTitle: "Austrian_State_Treaty",
  },
  {
    id: "first_geneva_convention",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "In a lakeside city, delegates signed a treaty protecting wounded soldiers and medics in war, leading directly to a famous aid organization still active today.",
    name: "First Geneva Convention",
    explanation: "The First Geneva Convention was signed in Geneva to guarantee humane treatment for wounded soldiers and protect medical personnel regardless of which side they served. It laid the legal foundation for what became the Red Cross movement.",
    year: 1864,
    lat: 46.2,
    lng: 6.15,
    wikipediaTitle: "First_Geneva_Convention",
  },
  {
    id: "convention_of_kanagawa",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "A fleet of foreign warships forced a long-isolated island nation to open two ports to trade, ending more than two centuries of near-total self-isolation.",
    name: "Convention of Kanagawa",
    explanation: "The Convention of Kanagawa was signed after a fleet of American warships anchored offshore and pressured the government into opening two ports to foreign trade, ending over two centuries during which the country had barred most contact with the outside world.",
    year: 1854,
    lat: 35.450333,
    lng: 139.634222,
    wikipediaTitle: "Convention_of_Kanagawa",
  },
  {
    id: "montevideo_convention",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "conflict_politics_society",
    clue: "In a coastal capital on a wide river estuary, delegates from nineteen nations signed a treaty defining what counts as a state, still cited by lawyers today.",
    name: "Montevideo Convention",
    explanation: "The Montevideo Convention was signed in Montevideo by nineteen countries. It set out the classic legal test for statehood, requiring a permanent population, a defined territory, a government, and the capacity to enter relations with other states, a definition still cited in international law today.",
    year: 1933,
    lat: -34.905917,
    lng: -56.191311,
    wikipediaTitle: "Montevideo_Convention",
  },
  {
    id: "minaret_of_jam",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "Deep in a remote mountain valley, a soaring brick minaret became one of the tallest ever built of that material, rediscovered by outsiders only decades ago.",
    name: "Minaret of Jam",
    explanation: "The Minaret of Jam stands more than 60 meters tall in a remote valley between two rivers in central Afghanistan. Built entirely of baked brick and covered in intricate calligraphy and geometric tilework, it went unknown to outside researchers until surprisingly recently.",
    year: 1194,
    lat: 34.396386,
    lng: 64.515888,
    wikipediaTitle: "Minaret_of_Jam",
  },
  {
    id: "khirokitia",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "On a small island, an early settlement built round, beehive-shaped stone houses and buried its dead directly beneath the floors people lived on.",
    name: "Khirokitia",
    explanation: "Khirokitia is one of the best-preserved early settlements in the eastern Mediterranean. Its round stone houses had no windows, and the dead were commonly buried in pits dug beneath the floors of the homes where they had lived.",
    year: -7001,
    lat: 34.796725,
    lng: 33.343719,
    wikipediaTitle: "Khirokitia",
  },
  {
    id: "bru_na_boinne",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "In a bend of a river, an ancient passage tomb was built so precisely aligned that sunlight only reaches its inner chamber on the shortest day of the year.",
    name: "Brú na Bóinne",
    explanation: "Brú na Bóinne, in a bend of the River Boyne, includes the passage tomb of Newgrange. Its inner chamber is built so precisely that sunlight enters through a special opening only around the winter solstice, illuminating the chamber for a few minutes each year.",
    year: -3500,
    lat: 53.69284,
    lng: -6.44932,
    wikipediaTitle: "Brú_na_Bóinne",
  },
  {
    id: "alodia_soba",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "A kingdom's capital rose near where two differently colored rivers merge into one of the world's famous rivers, and thrived for centuries as a regional power.",
    name: "Alodia",
    explanation: "Alodia was a kingdom in what is now central Sudan. Its capital, Soba, stood on the Blue Nile a short distance upstream from where it meets the White Nile to form the Nile itself. The kingdom endured for centuries before eventually declining and fading from regional power.",
    year: 600,
    lat: 15.52389,
    lng: 32.68083,
    wikipediaTitle: "Alodia",
  },
  {
    id: "danevirke",
    pinIsBirthplace: false,
    difficulty: "hard",
    category: "science_infrastructure",
    clue: "Across the narrow neck of a peninsula, a massive defensive earthwork was expanded over a thousand years to block the only land route into the region.",
    name: "Danevirke",
    explanation: "The Danevirke is a system of earthwork fortifications built across the base of a peninsula to block the only land route into the region from the south. First raised in the early medieval period, it was expanded repeatedly over more than a thousand years and last saw military use in a war fought long after its original construction.",
    year: 600,
    lat: 54.4775,
    lng: 9.486667,
    wikipediaTitle: "Danevirke",
  },
  {
    id: "buddha_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "arts_culture",
    clue: "Born into royalty at the foot of the Himalayas, he renounced his wealth to seek awakening, founding one of the world's largest religions after meditating.",
    name: "The Buddha",
    explanation: "Siddhartha Gautama was born in Lumbini, the son of a ruling clan's leader. He left his palace life to become a wandering ascetic, and his teachings on suffering and liberation became the foundation of Buddhism, now practiced by hundreds of millions of people worldwide.",
    year: -501,
    lat: 27.4814,
    lng: 83.275829,
    wikipediaTitle: "The_Buddha",
  },
  {
    id: "michelangelo_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "arts_culture",
    clue: "Born in a small village, this sculptor carved a masterpiece from a flawed marble block others had rejected, then spent years painting a huge fresco overhead.",
    name: "Michelangelo",
    explanation: "Michelangelo was born in the village of Caprese. He carved his famous statue from a block of marble that two earlier sculptors had given up on as ruined, and later painted the ceiling of a major chapel almost entirely by himself.",
    year: 1475,
    lat: 43.640833,
    lng: 11.985833,
    wikipediaTitle: "Michelangelo",
  },
  {
    id: "beethoven_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "arts_culture",
    clue: "Born in a small city on the Rhine, this composer kept creating some of history's most celebrated music even after going completely deaf.",
    name: "Ludwig van Beethoven",
    explanation: "Ludwig van Beethoven was born in Bonn. He began losing his hearing in his twenties and was almost completely deaf by the time he composed some of his most famous symphonies, reportedly feeling the vibrations of the orchestra through the floor.",
    year: 1770,
    lat: 50.735278,
    lng: 7.102222,
    wikipediaTitle: "Ludwig_van_Beethoven",
  },
  {
    id: "wilde_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "arts_culture",
    clue: "Born into a well-off family, this playwright became one of the most quoted writers of his time, later imprisoned for his sexuality under the laws of that era.",
    name: "Oscar Wilde",
    explanation: "Oscar Wilde was born in Dublin. Famous for his sharp wit and plays, he was later convicted and imprisoned for his relationships with men, at a time when such relationships were criminalized, an experience he wrote about after his release.",
    year: 1854,
    lat: 53.349722,
    lng: -6.260278,
    wikipediaTitle: "Oscar_Wilde",
  },
  {
    id: "andersen_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "arts_culture",
    clue: "Born poor, this writer turned folk tales into fairy tales about mermaids, ugly ducklings, and bare emperors, now translated into countless languages worldwide.",
    name: "Hans Christian Andersen",
    explanation: "Hans Christian Andersen was born in Odense to a poor family. His fairy tales, many adapted from older folk material, have been translated into more languages than almost any other work of literature.",
    year: 1805,
    lat: 55.4,
    lng: 10.383333,
    wikipediaTitle: "Hans_Christian_Andersen",
  },
  {
    id: "stonehenge",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "A ring of massive standing stones, some hauled from hundreds of kilometers away, was built to align with the sun on the year's longest day.",
    name: "Stonehenge",
    explanation: "Stonehenge stands on Salisbury Plain. Some of its smaller bluestones were transported from quarries roughly 200 kilometers away, an extraordinary feat for the technology of the time, and the monument remains aligned with the solstice sunrise and sunset.",
    year: -1849,
    lat: 51.178889,
    lng: -1.826111,
    wikipediaTitle: "Stonehenge",
  },
  {
    id: "pompeii",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "A thriving ancient city was buried so suddenly under volcanic ash that its buildings, art, and even the shapes of victims' bodies were preserved for centuries.",
    name: "Pompeii",
    explanation: "Pompeii was buried under meters of ash and pumice after a nearby volcano erupted. The ash hardened around organic material that later decayed, leaving cavities that archaeologists filled with plaster to reveal the exact poses of people and animals at the moment of the disaster.",
    year: -601,
    lat: 40.750556,
    lng: 14.489722,
    wikipediaTitle: "Pompeii",
  },
  {
    id: "darwin_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Born wealthy, this naturalist spent five years sailing the world collecting specimens, then published a theory explaining how living species evolve over time.",
    name: "Charles Darwin",
    explanation: "Charles Darwin was born in Shrewsbury. His round-the-world voyage as a young naturalist gave him the observations that led, decades later, to his theory of evolution by natural selection.",
    year: 1809,
    lat: 52.7128,
    lng: -2.76334,
    wikipediaTitle: "Charles_Darwin",
  },
  {
    id: "edison_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Born into a large family, this inventor held over a thousand patents, including the light bulb, the phonograph, and an early motion picture camera.",
    name: "Thomas Edison",
    explanation: "Thomas Edison was born in Milan, Ohio. He built one of the first industrial research laboratories, where teams of workers helped him develop and patent inventions at a remarkable pace throughout his career.",
    year: 1847,
    lat: 41.29306,
    lng: -82.60111,
    wikipediaTitle: "Thomas_Edison",
  },
  {
    id: "copernicus_birth",
    pinIsBirthplace: true,
    difficulty: "easy",
    category: "science_infrastructure",
    clue: "Born into a merchant family, this astronomer proposed that the sun, not the earth, was the center of the universe, a theory published only as he lay dying.",
    name: "Nicolaus Copernicus",
    explanation: "Nicolaus Copernicus was born in Toruń. He worked on his heliocentric model for decades but delayed publishing it for fear of ridicule, reportedly receiving a printed copy of his book only on the day he died.",
    year: 1473,
    lat: 53.0144,
    lng: 18.6014,
    wikipediaTitle: "Nicolaus_Copernicus",
  },
  {
    id: "pearl_harbor",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "In the middle of a vast ocean, a surprise air attack on a naval base sank or damaged nearly twenty warships in two hours, drawing a neutral nation into war.",
    name: "Attack on Pearl Harbor",
    explanation: "The attack on Pearl Harbor targeted the fleet at anchor on a quiet Sunday morning. The surprise assault destroyed or damaged nearly the entire battleship fleet stationed there and brought the United States into the war the following day.",
    year: 1941,
    lat: 21.365,
    lng: -157.95,
    wikipediaTitle: "Attack_on_Pearl_Harbor",
  },
  {
    id: "agincourt",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "A heavily outnumbered army of archers cut down thousands of knights so bogged down in deep mud that many suffocated under the weight of the fallen.",
    name: "Battle of Agincourt",
    explanation: "At Agincourt, a smaller force relied on massed longbowmen to break the charge of heavily armored knights struggling through deep, freshly plowed mud. So many fell and could not rise under their own armor's weight that some were crushed or suffocated beneath piles of their own comrades.",
    year: 1415,
    lat: 50.463333,
    lng: 2.141389,
    wikipediaTitle: "Battle_of_Agincourt",
  },
  {
    id: "little_bighorn",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "A famous cavalry commander and his entire battalion were wiped out in under an hour after attacking a vastly larger encampment of allied Indigenous nations.",
    name: "Battle of the Little Bighorn",
    explanation: "At the Little Bighorn, a cavalry regiment led by a general famous for earlier victories split his forces and attacked a huge encampment, underestimating its size. He and roughly 200 of his men were killed in the ensuing fight.",
    year: 1876,
    lat: 45.565,
    lng: -107.428889,
    wikipediaTitle: "Battle_of_the_Little_Bighorn",
  },
  {
    id: "franz_ferdinand",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "A royal heir was assassinated by a teenage nationalist hours after an earlier bomb attempt failed, an act often cited as the spark that ignited a world war.",
    name: "Assassination of Franz Ferdinand",
    explanation: "Archduke Franz Ferdinand survived an earlier grenade attack that morning, then was shot along with his wife later the same day after his driver took a wrong turn straight past the gunman. The killing set off a chain of alliances that pulled much of the world into war within weeks.",
    year: 1914,
    lat: 43.857917,
    lng: 18.428861,
    wikipediaTitle: "Assassination_of_Archduke_Franz_Ferdinand",
  },
  {
    id: "gettysburg",
    pinIsBirthplace: false,
    difficulty: "easy",
    category: "conflict_politics_society",
    clue: "Fought over three days, this battle produced more casualties than any other in a bloody civil war, and later hosted one of history's most quoted short speeches.",
    name: "Battle of Gettysburg",
    explanation: "The Battle of Gettysburg turned back an invasion of the North and is often seen as the war's turning point. Months later, the president delivered a short speech at the dedication of the battlefield's cemetery that became one of the most quoted in the country's history.",
    year: 1863,
    lat: 39.811389,
    lng: -77.225833,
    wikipediaTitle: "Battle_of_Gettysburg",
  },
];

export type GameMode = "daily" | "archive";

export function pickRandomEvents(events: HistoricalEvent[], count: number, excludeIds: string[] = []): HistoricalEvent[] {
  const excluded = new Set(excludeIds);
  const pool = events.filter((e) => !excluded.has(e.id));
  // If exclusions would leave too few events to fill a round, ignore them
  // rather than block the game — repeats are a minor annoyance, an empty
  // pool isn't an option.
  const source = pool.length >= count ? pool : events;
  const shuffled = [...source];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}

// Deterministic day-of-year seed (UTC) so every player gets the same shuffle
// on the same calendar day without any server round-trip.
function dailySeed(date: Date): number {
  const key = date.toISOString().slice(0, 10); // "YYYY-MM-DD"
  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = (Math.imul(hash, 31) + key.charCodeAt(i)) | 0;
  }
  return hash;
}

// xmur3-ish mix into mulberry32, seeded from dailySeed — good enough
// distribution for shuffling a few dozen events, not cryptographic.
function seededRandom(seed: number): () => number {
  let state = seed | 0;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle<T>(arr: T[], random: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Days since the Unix epoch, from the same UTC calendar-day key dailySeed()
// uses, so pack rotation and the daily-reset boundary always agree.
function daysSinceEpoch(date: Date): number {
  const key = date.toISOString().slice(0, 10); // "YYYY-MM-DD"
  return Math.floor(Date.parse(`${key}T00:00:00.000Z`) / 86400000);
}

export function pickDailyEvents(events: HistoricalEvent[], count: number, date: Date = new Date()): HistoricalEvent[] {
  const packs = DAILY_PACKS_PLAN.packs;
  const totalPacks = packs.length;

  if (totalPacks > 0) {
    // One pack = one day. Packs cycle in a seeded-shuffled order per full
    // pass over the plan, so no pack repeats until every pack in the plan
    // has been played once.
    const dayIndex = daysSinceEpoch(date);
    const cycleNumber = Math.floor(dayIndex / totalPacks);
    const cycleIndex = dayIndex % totalPacks;
    const order = shuffle(
      Array.from({ length: totalPacks }, (_, i) => i),
      seededRandom(cycleNumber),
    );
    const pack = packs[order[cycleIndex]];
    const byId = new Map(events.map((e) => [e.id, e]));
    const picked = pack.ids.map((id) => byId.get(id)).filter((e): e is HistoricalEvent => Boolean(e));
    if (picked.length === count) return picked;
    // Plan is stale relative to the current pool (ids removed/renamed) —
    // fall back rather than serve a short round.
  }

  const random = seededRandom(dailySeed(date));
  const shuffled = [...events];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}
