#!/usr/bin/env node
// Extracts just id + name + year from src/lib/poc-events.ts (no clue/explanation
// text) into docs/used-topics.md — a lightweight reference for checking whether
// a subject has already been covered, without reading the full events file.
//
// Usage: node scripts/list-topics.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EN_PATH = path.join(__dirname, "..", "src", "lib", "poc-events.ts");
const OUT_PATH = path.join(__dirname, "..", "docs", "used-topics.md");

function sliceBlocks(content, idRe) {
  const matches = [...content.matchAll(idRe)];
  const blocks = [];
  for (let i = 0; i < matches.length; i++) {
    const id = matches[i][1];
    const start = matches[i].index;
    const end = i + 1 < matches.length ? matches[i + 1].index : content.length;
    blocks.push({ id, block: content.slice(start, end) });
  }
  return blocks;
}

function extractString(block, field) {
  const re = new RegExp(`${field}:\\s*\\n?\\s*"((?:\\\\.|[^"\\\\])*)"`);
  const m = block.match(re);
  return m ? m[1] : null;
}

function extractNumber(block, field) {
  const re = new RegExp(`${field}:\\s*(-?\\d+)`);
  const m = block.match(re);
  return m ? Number(m[1]) : null;
}

function main() {
  const content = readFileSync(EN_PATH, "utf8");
  const blocks = sliceBlocks(content, /id:\s*"([a-zA-Z0-9_]+)"/g);

  const entries = blocks.map(({ id, block }) => ({
    id,
    name: extractString(block, "name"),
    year: extractNumber(block, "year"),
  }));

  entries.sort((a, b) => (a.year ?? 0) - (b.year ?? 0));

  const lines = entries.map((e) => `- ${e.year} — ${e.name} (${e.id})`);
  const out = `<!-- Auto-generated by scripts/list-topics.mjs. Do not edit by hand. -->\n` +
    `# Used topics (${entries.length})\n\n` +
    lines.join("\n") + "\n";

  writeFileSync(OUT_PATH, out, "utf8");
  console.log(`list-topics: wrote ${entries.length} entries to docs/used-topics.md`);
}

main();
